# -*- coding: utf-8 -*-
"""Catalogue A - Parcours 1 « Comprendre l'IA » (5 cours débutant)
+ 2 premiers cours du Parcours 2 « L'art du prompt ».
Ton Ordria : direct, zéro jargon, exemples métiers TPE/PME/artisans, résultats concrets.
Interdit : le caractère em dash (tiret long)."""
from factory import (doc, heading, para, bullets, ordered, callout_info,
                     callout_warning, image, quiz_node)

COURSES = [
# ═══════════════ PARCOURS 1 : COMPRENDRE L'IA ═══════════════
{
 "slug": "ia-quotidien-metier",
 "title": "L'IA au quotidien : ce que ça change pour votre métier",
 "level": "Débutant",
 "description": "Vous entendez parler d'IA partout sans savoir ce que ça peut vraiment faire pour vous ? Ce cours démontre, exemples concrets à l'appui, ce qu'un assistant IA change dans la journée d'un artisan, d'un commerçant ou d'un dirigeant de TPE. Objectif : passer de la curiosité au premier usage utile dès ce soir.",
 "learnings": "Identifier 5 tâches de votre journée déléguables à l'IA, comprendre ce que l'IA fait bien et mal, gagner 2 à 4 heures par semaine sur l'administratif, choisir votre premier cas d'usage, éviter les fausses promesses",
 "tags": "ia, débutant, parcours-comprendre-lia, metiers, automatisation",
 "cover_query": "artisan workshop tools",
 "chapters": [
  {
   "title": "Pourquoi tout le monde parle d'IA",
   "description": "Séparer le vrai du buzz et voir ce que l'IA fait déjà dans des entreprises comme la vôtre.",
   "activities": [
    {
     "title": "Le vrai visage de l'IA au travail",
     "image_query": "small business owner laptop",
     "build": lambda img: doc(
        heading(1, "Le vrai visage de l'IA au travail"),
        para("Oubliez les robots de science-fiction. L'IA qui vous intéresse, c'est un assistant textuel : vous lui décrivez une tâche, il la rédige, la calcule, la résume ou la met en forme. Comme un stagiaire très rapide, disponible 24h/24, mais qu'il faut superviser."),
        image(img),
        heading(2, "Ce qu'un assistant IA fait déjà aujourd'hui"),
        bullets([
            "Rédiger un devis, un email client ou une relance en quelques secondes",
            "Résumer un appel, un devis fournisseur ou un contrat en 5 lignes",
            "Classer et mettre en forme vos documents (factures, bons de commande)",
            "Répondre aux questions récurrentes de vos clients",
            "Préparer des annonces, des posts, des fiches produit",
        ]),
        heading(2, "Ce qu'il ne faut PAS lui demander"),
        bullets([
            "Des chiffres exacts sans vérification : il peut inventer (on appelle ça une hallucination)",
            "Des décisions juridiques ou fiscales sans relecture d'un professionnel",
            "Vos mots de passe ou vos données clients sensibles",
        ]),
        callout_info("Astuce Ordria : commencez par UNE tâche pénible et répétitive. Un seul gain concret vaut mieux que dix essais dispersés."),
        callout_warning("Piège à éviter : croire que l'IA va « tout automatiser » seule. C'est un outil : c'est vous qui gardez la main."),
     ),
    },
    {
     "title": "Combien de temps ça vaut vraiment",
     "image_query": "craftsman working hands",
     "build": lambda img: doc(
        heading(1, "Combien de temps ça vaut vraiment"),
        para("Un devis traiteur rédigé à la main : 20 minutes. Avec un assistant IA et vos tarifs : 3 minutes. Une relance client : 10 minutes contre 1 minute. Sur une semaine, les entreprises qui délèguent l'administratif récupèrent entre 5 et 10 heures."),
        image(img),
        heading(2, "Le calcul simple à faire chez vous"),
        ordered([
            "Listez les tâches répétitives de votre semaine (devis, emails, factures, comptes rendus)",
            "Notez le temps passé sur chacune",
            "Multipliez par 4 pour le mois, puis par 12 pour l'année",
        ]),
        para("La plupart des patrons de TPE découvrent qu'ils passent l'équivalent de 2 jours par mois sur des tâches qu'un assistant IA peut préparer à 80 %."),
        callout_info("Repère Ordria : nos clients récupèrent en moyenne 10 heures par semaine après automatisation du devis, des relances et de la facturation."),
     ),
    },
    {
     "title": "Quiz : l'IA au quotidien",
     "build": lambda img: doc(
        heading(1, "Quiz : l'IA au quotidien"),
        para("Cinq questions pour vérifier que les bases sont claires avant de passer au prompt."),
        quiz_node([
            {"q": "Quelle est la meilleure première tâche à déléguer à un assistant IA ?",
             "answers": [{"a": "Une tâche répétitive et pénible, comme rédiger des devis", "c": True},
                        {"a": "La comptabilité officielle", "c": False},
                        {"a": "Les décisions d'embauche", "c": False},
                        {"a": "La relation avec votre banquier", "c": False}]},
            {"q": "Qu'est-ce qu'une hallucination en IA ?",
             "answers": [{"a": "Un bug d'affichage", "c": False},
                        {"a": "Une réponse inventée mais présentée comme exacte", "c": True},
                        {"a": "Une lenteur de réponse", "c": False},
                        {"a": "Une coupure d'internet", "c": False}]},
            {"q": "Combien de temps une TPE récupère-t-elle typiquement en automatisant devis, relances et factures ?",
             "answers": [{"a": "10 minutes par semaine", "c": False},
                        {"a": "Environ 10 heures par semaine", "c": True},
                        {"a": "Rien du tout", "c": False},
                        {"a": "3 jours par semaine", "c": False}]},
            {"q": "Que doit-on toujours faire avant d'envoyer un document généré par l'IA ?",
             "answers": [{"a": "Le relire et vérifier les chiffres", "c": True},
                        {"a": "Rien, l'IA est fiable à 100 %", "c": False},
                        {"a": "L'imprimer d'abord", "c": False},
                        {"a": "Le poster sur les réseaux sociaux", "c": False}]},
            {"q": "Quelle donnée ne faut-il JAMAIS donner à un assistant IA public ?",
             "answers": [{"a": "Le nom de votre ville", "c": False},
                        {"a": "Vos tarifs publics", "c": False},
                        {"a": "Des mots de passe ou des données clients sensibles", "c": True},
                        {"a": "Vos horaires d'ouverture", "c": False}]},
        ]),
     ),
    },
   ],
  },
  {
   "title": "Vos premiers pas concrets",
   "description": "Choisir son outil, créer son compte et réussir sa première demande.",
   "activities": [
    {
     "title": "Choisir et prendre en main son assistant",
     "image_query": "person using smartphone business",
     "build": lambda img: doc(
        heading(1, "Choisir et prendre en main son assistant"),
        para("Trois grands assistants grand public se valent pour commencer : ChatGPT, Claude et Gemini. Tous fonctionnent comme une messagerie : vous tapez une demande, l'assistant répond. La version gratuite suffit pour apprendre."),
        image(img),
        heading(2, "Votre première session en 4 étapes"),
        ordered([
            "Créez un compte avec votre email professionnel",
            "Tapez une demande simple : « Résume ce texte en 5 lignes » suivi d'un email que vous avez reçu",
            "Notez ce qui vous a plu et ce qui manque dans la réponse",
            "Reformulez votre demande en ajoutant du contexte (votre métier, votre ton, le destinataire)",
        ]),
        callout_info("Astuce Ordria : sur mobile, installez l'application et essayez le micro pour dicter. Beaucoup d'artisans préfèrent parler que taper."),
        callout_warning("Piège à éviter : rester sur « Bonjour ». Plus votre demande est précise, meilleure est la réponse. Le cours suivant vous donne la méthode."),
     ),
    },
    {
     "title": "Votre premier gain de temps ce soir",
     "image_query": "evening office desk lamp",
     "build": lambda img: doc(
        heading(1, "Votre premier gain de temps ce soir"),
        para("Exercice pratique : ce soir, prenez la dernière tâche administrative qui vous a agacé. Un email difficile à formuler, une réponse à un client mécontent, une annonce. Faites-la préparer par l'assistant, corrigez, envoyez."),
        image(img),
        heading(2, "Exemple : répondre à un client mécontent"),
        ordered([
            "Collez le message du client dans l'assistant",
            "Ajoutez : « Tu es gérant d'une entreprise de plomberie. Rédige une réponse calme, professionnelle, qui propose un rendez-vous téléphonique »",
            "Ajustez le ton s'il est trop froid ou trop long",
            "Relisez une fois et envoyez",
        ]),
        para("Temps total : 3 minutes au lieu de 20, et un message mieux formulé que ce que la fatigue du soir aurait produit."),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "fonctionnement-assistant-ia",
 "title": "Comment fonctionne un assistant IA, sans jargon",
 "level": "Débutant",
 "description": "Pas de mathématiques, promis. Ce cours explique avec des images simples comment l'IA « lit », « comprend » et « rédige », pourquoi elle se trompe parfois et pourquoi la façon de poser la question change tout.",
 "learnings": "Comprendre le mécanisme de prédiction de mots, savoir pourquoi l'IA invente parfois, distinguer ce qu'elle sait de ce qu'elle ne sait pas, expliquer l'IA à un collègue en 2 minutes",
 "tags": "ia, débutant, parcours-comprendre-lia, vulgarisation",
 "cover_query": "library books knowledge",
 "chapters": [
  {
   "title": "La machine à compléter du texte",
   "description": "Le mécanisme central, expliqué comme à un client.",
   "activities": [
    {
     "title": "Prédire le mot suivant : le moteur de l'IA",
     "image_query": "typewriter keys closeup",
     "build": lambda img: doc(
        heading(1, "Prédire le mot suivant : le moteur de l'IA"),
        para("Un assistant IA est un ordinateur entraîné sur des milliards de textes : livres, articles, sites web. Son unique mécanisme : prédire, mot après mot, la suite la plus probable. Comme le clavier de votre téléphone qui suggère le mot suivant, mais avec une mémoire et une culture générale immenses."),
        image(img),
        heading(2, "La conséquence n°1 : l'IA ne « sait » rien"),
        para("Elle ne consulte pas une base de vérités. Elle produit du texte plausible. Si le sujet est bien documenté, la réponse est généralement juste. Si vous demandez un chiffre rare, elle peut en produire un crédible mais faux."),
        heading(2, "La conséquence n°2 : la question oriente la réponse"),
        para("Comme elle suit les probabilités, une question vague donne une réponse vague. Une question précise, avec contexte et exemples, canalise la prédiction vers ce que VOUS attendez. C'est tout l'art du prompt."),
        callout_info("Image mentale Ordria : l'IA est un collaborateur brillant qui a tout lu mais ne connaît rien à VOTRE entreprise. À vous de lui donner le contexte."),
     ),
    },
    {
     "title": "Pourquoi l'IA se trompe (et comment le repérer)",
     "image_query": "magnifying glass document",
     "build": lambda img: doc(
        heading(1, "Pourquoi l'IA se trompe (et comment le repérer)"),
        para("Les erreurs de l'IA sont prévisibles et se repèrent avec de simples réflexes. Ce sont presque toujours des cas où la prédiction « plausible » a remplacé le fait vérifiable."),
        image(img),
        heading(2, "Les 4 signaux d'alerte"),
        bullets([
            "Un chiffre précis sans source (prix, date, loi, statistique)",
            "Une liste trop parfaite ou trop générique",
            "Des noms propres rares (personnes, entreprises, références légales)",
            "Un ton très assuré sur un sujet pointu",
        ]),
        heading(2, "Le réflexe des pros"),
        ordered([
            "Demander à l'IA de citer ses points d'incertitude",
            "Vérifier tout chiffre ou référence avant usage client",
            "Garder la main sur la version finale : vous signez, pas l'IA",
        ]),
        callout_warning("Règle Ordria : l'IA rédige le brouillon, l'humain valide. Toujours."),
     ),
    },
    {
     "title": "Quiz : comprendre la machine",
     "build": lambda img: doc(
        heading(1, "Quiz : comprendre la machine"),
        quiz_node([
            {"q": "Que fait concrètement un assistant IA quand il répond ?",
             "answers": [{"a": "Il consulte une encyclopédie vérifiée", "c": False},
                        {"a": "Il prédit le mot suivant le plus probable", "c": True},
                        {"a": "Il cherche sur internet en direct", "c": False},
                        {"a": "Il interroge votre banque", "c": False}]},
            {"q": "Pourquoi une réponse vague à une question vague ?",
             "answers": [{"a": "Parce que l'IA est paresseuse", "c": False},
                        {"a": "Parce que la prédiction suit le flou de la question", "c": True},
                        {"a": "Parce que le wifi est lent", "c": False},
                        {"a": "Parce que la version est gratuite", "c": False}]},
            {"q": "Quel type d'information doit TOUJOURS être vérifié ?",
             "answers": [{"a": "Les chiffres précis sans source", "c": True},
                        {"a": "Les formules de politesse", "c": False},
                        {"a": "Les synonymes", "c": False},
                        {"a": "La mise en forme des listes", "c": False}]},
            {"q": "Quelle phrase résume la bonne méthode de travail ?",
             "answers": [{"a": "L'IA décide, l'humain exécute", "c": False},
                        {"a": "L'IA rédige le brouillon, l'humain valide", "c": True},
                        {"a": "L'humain rédige, l'IA signe", "c": False},
                        {"a": "Personne ne vérifie, on gagne du temps", "c": False}]},
            {"q": "L'IA a-t-elle connaissance de votre entreprise sans contexte ?",
             "answers": [{"a": "Oui, elle a tout lu", "c": False},
                        {"a": "Non, elle ne connaît rien à VOTRE activité tant que vous ne le dites pas", "c": True},
                        {"a": "Seulement si vous payez", "c": False},
                        {"a": "Uniquement le week-end", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "confiance-et-verification-ia",
 "title": "Peut-on faire confiance à l'IA ? Vérifier sans y passer sa journée",
 "level": "Débutant",
 "description": "Faire confiance sans naïveté : la méthode de vérification rapide des pros, les zones à risque (chiffres, lois, noms) et le réflexe à avoir avant chaque envoi client.",
 "learnings": "Appliquer la vérification en 30 secondes, repérer les hallucinations, savoir quand refuser l'IA, bâtir une confiance progressive fondée sur l'expérience",
 "tags": "ia, débutant, parcours-comprendre-lia, fiabilité, verification",
 "cover_query": "checklist clipboard verification",
 "chapters": [
  {
   "title": "La vérification qui prend 30 secondes",
   "description": "La méthode simple avant chaque envoi.",
   "activities": [
    {
     "title": "La règle des 3 verrous",
     "image_query": "handshake business trust",
     "build": lambda img: doc(
        heading(1, "La règle des 3 verrous"),
        para("Avant d'envoyer un document généré par IA, trois vérifications suffisent dans 95 % des cas. Trente secondes, pas plus."),
        image(img),
        heading(2, "Verrou 1 : les chiffres"),
        para("Tout montant, toute date, toute quantité : vérifiez sur votre source (devis signé, bon de commande, facture). L'IA arrondit, transforme, parfois inverse."),
        heading(2, "Verrou 2 : les noms"),
        para("Noms de clients, d'entreprises, de produits : une lettre inversée et le document part à la mauvaise personne."),
        heading(2, "Verrou 3 : les promesses"),
        para("L'IA a un tendance à enjoliver : délais, garanties, engagements. Toute promesse écrite vous engage VOUS."),
        callout_info("Astuce Ordria : lisez le document final à voix haute. L'oreille attrape les anomalies que l'œil survole."),
     ),
    },
    {
     "title": "Les zones rouges : quand ne PAS utiliser l'IA",
     "image_query": "warning sign road",
     "build": lambda img: doc(
        heading(1, "Les zones rouges : quand ne PAS utiliser l'IA"),
        para("Certaines tâches se prêtent mal à l'IA seule. Pas d'interdit dogmatique : simplement, ces zones exigent un humain responsable et informé."),
        image(img),
        bullets([
            "Conseils juridiques et fiscaux : l'IA prépare, votre expert-comptable ou avocat valide",
            "Données médicales ou personnelles sensibles : prudence RGPD maximale",
            "Prix et conditions contractuelles définitives : décision humaine",
            "Communication de crise : l'IA prépare un brouillon, vous gardez la voix",
        ]),
        callout_warning("Rappel RGPD simple : ne collez jamais des données identifiantes de vos clients (nom complet, adresse, santé) dans un assistant grand public. Anonymisez : « un client du secteur BTP » plutôt que le nom."),
        para("Pour le reste, la confiance se construit : après 20 documents vérifiés sans erreur, vous saurez exactement à quoi cet outil sert dans VOTRE métier."),
     ),
    },
    {
     "title": "Quiz : confiance et vérification",
     "build": lambda img: doc(
        heading(1, "Quiz : confiance et vérification"),
        quiz_node([
            {"q": "Quels sont les 3 verrous de vérification rapide ?",
             "answers": [{"a": "Chiffres, noms, promesses", "c": True},
                        {"a": "Orthographe, papier, timbre", "c": False},
                        {"a": "Couleur, logo, signature", "c": False},
                        {"a": "Prix, photo, email", "c": False}]},
            {"q": "Que faire d'un conseil juridique rédigé par l'IA ?",
             "answers": [{"a": "L'envoyer tel quel", "c": False},
                        {"a": "Le faire valider par un professionnel", "c": True},
                        {"a": "Le poster sur LinkedIn", "c": False},
                        {"a": "Le signer immédiatement", "c": False}]},
            {"q": "Comment traiter des données clients dans un assistant public ?",
             "answers": [{"a": "Les coller telles quelles", "c": False},
                        {"a": "Les anonymiser avant toute utilisation", "c": True},
                        {"a": "Les chiffrer à la main", "c": False},
                        {"a": "Demander l'autorisation à l'IA", "c": False}]},
            {"q": "Pourquoi lire le document final à voix haute ?",
             "answers": [{"a": "Pour impressionner le voisinage", "c": False},
                        {"a": "Parce que l'oreille repère des anomalies que l'œil survole", "c": True},
                        {"a": "Pour mémoriser le texte", "c": False},
                        {"a": "C'est inutile", "c": False}]},
            {"q": "Comment se construit la confiance en l'IA ?",
             "answers": [{"a": "D'un coup, en lisant le manuel", "c": False},
                        {"a": "Progressivement, en vérifiant chaque document au début", "c": True},
                        {"a": "En désactivant la vérification", "c": False},
                        {"a": "En payant un abonnement premium", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "donnees-rgpd-simplement",
 "title": "Vos données et l'IA : confidentialité et RGPD simplement",
 "level": "Débutant",
 "description": "Ce que deviennent vos textes quand vous les collez dans un assistant, ce que dit le RGPD en pratique, et les bons réflexes pour utiliser l'IA sans exposer vos clients ni votre entreprise.",
 "learnings": "Comprendre où vont vos données, appliquer 5 réflexes RGPD simples, choisir un outil selon la sensibilité de l'information, savoir quand anonymiser",
 "tags": "ia, débutant, parcours-comprendre-lia, rgpd, donnees, confidentialite",
 "cover_query": "lock security digital",
 "chapters": [
  {
   "title": "Où vont vos textes",
   "description": "Le trajet d'une donnée collée dans un assistant, en clair.",
   "activities": [
    {
     "title": "Le voyage d'une donnée",
     "image_query": "server room data center",
     "build": lambda img: doc(
        heading(1, "Le voyage d'une donnée"),
        para("Quand vous envoyez un texte à un assistant IA, il transite vers les serveurs de l'éditeur (souvent aux États-Unis), il sert à produire la réponse, et selon les outils il peut être conservé pour améliorer les modèles. La donnée elle-même n'est pas « publiée », mais elle quitte votre contrôle."),
        image(img),
        heading(2, "Les 3 questions à se poser avant de coller"),
        ordered([
            "Cette information est-elle publique ? (une fiche produit : aucun risque)",
            "Contient-elle des données personnelles ? (noms, coordonnées, santé : anonymiser)",
            "Contient-elle un secret professionnel ou stratégique ? (tarifs négociés, procédés : s'abstenir ou utiliser un outil pro hébergé en Europe)",
        ]),
        callout_info("Réflexe simple : si vous hésitez à le dire au téléphone dans un lieu public, ne le collez pas dans un assistant grand public."),
     ),
    },
    {
     "title": "RGPD pratique : les 5 réflexes",
     "image_query": "europe flag building",
     "build": lambda img: doc(
        heading(1, "RGPD pratique : les 5 réflexes"),
        para("Le RGPD demande que les données personnelles de vos clients soient protégées. Avec l'IA, cinq réflexes suffisent à couvrir l'essentiel en TPE."),
        image(img),
        ordered([
            "Anonymiser : « un client particulier de Lyon » plutôt que son nom et adresse",
            "Minimiser : ne coller que le strict nécessaire à la tâche",
            "Préférer, pour les usages intensifs, des outils avec engagement de non-réutilisation et hébergement européen",
            "Informer : si un outil IA traite des données clients dans un cadre défini, mentionnez-le dans votre politique de confidentialité",
            "Supprimer : ne stockez pas des conversations sensibles « au cas où »",
        ]),
        callout_info("Ordria héberge les données de ses clients en France et applique son bouclier RGPD : c'est le standard que nous recommandons d'exiger de tout prestataire."),
        callout_warning("Le bouclier RGPD d'Ordria ne vous dispense pas de vos propres réflexes : la première protection, c'est vous."),
     ),
    },
    {
     "title": "Quiz : données et RGPD",
     "build": lambda img: doc(
        heading(1, "Quiz : données et RGPD"),
        quiz_node([
            {"q": "Que devient un texte collé dans un assistant IA public ?",
             "answers": [{"a": "Il reste sur votre ordinateur", "c": False},
                        {"a": "Il transite vers les serveurs de l'éditeur et peut y être conservé", "c": True},
                        {"a": "Il est imprimé", "c": False},
                        {"a": "Il est effacé instantanément", "c": False}]},
            {"q": "Que faire d'un nom de client avant de coller un email dans l'IA ?",
             "answers": [{"a": "Rien, c'est sans importance", "c": False},
                        {"a": "L'anonymiser (ex. « un client du secteur X »)", "c": True},
                        {"a": "L'écrire en majuscules", "c": False},
                        {"a": "Le traduire en anglais", "c": False}]},
            {"q": "Quel hébergement privilégier pour des données sensibles ?",
             "answers": [{"a": "Peu importe", "c": False},
                        {"a": "Un outil avec engagement de non-réutilisation, hébergé en Europe", "c": True},
                        {"a": "Le moins cher", "c": False},
                        {"a": "Celui avec le plus de publicités", "c": False}]},
            {"q": "Que signifie « minimiser » au sens RGPD ?",
             "answers": [{"a": "Écrire le moins possible", "c": False},
                        {"a": "Ne transmettre que les données strictement nécessaires", "c": True},
                        {"a": "Réduire la taille de la police", "c": False},
                        {"a": "Payer moins d'impôts", "c": False}]},
            {"q": "Où Ordria héberge-t-il les données de ses clients ?",
             "answers": [{"a": "En France", "c": True},
                        {"a": "Sur la Lune", "c": False},
                        {"a": "Nulle part", "c": False},
                        {"a": "Chez le voisin", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "couts-et-limites-ia",
 "title": "Coûts et limites : abonnements, tokens et quand ça vaut le coup",
 "level": "Débutant",
 "description": "Versions gratuites ou payantes, à la lettre ou au forfait : comprendre comment on paie l'IA, estimer ce que ça coûte pour votre usage, et décider lucidement.",
 "learnings": "Comprendre le modèle économique des assistants IA, estimer son coût mensuel réel, savoir quand la version gratuite suffit, anticiper les limites techniques",
 "tags": "ia, débutant, parcours-comprendre-lia, couts, budget",
 "cover_query": "calculator coins budget",
 "chapters": [
  {
   "title": "Comment on paie l'IA",
   "description": "Forfaits, consommation et pièges de facturation.",
   "activities": [
    {
     "title": "Forfaits et consommations : le menu expliqué",
     "image_query": "coffee shop payment phone",
     "build": lambda img: doc(
        heading(1, "Forfaits et consommations : le menu expliqué"),
        para("Deux façons de payer l'IA : l'abonnement forfaitaire (une dizaine à une trentaine d'euros par mois pour un usage illimité ou quasi) ou la consommation (on paie chaque morceau de texte, méthode des développeurs et des automatisations)."),
        image(img),
        heading(2, "Le « token », l'unité de mesure"),
        para("Les assistants comptent en tokens : environ 3 quarts de mot chacun. Une page de devis : environ 800 tokens. Une conversation complète : quelques milliers. Cela sert surtout aux usages automatisés, facturés au volume."),
        heading(2, "Que choisir pour votre TPE ?"),
        bullets([
            "Apprentissage et usages quotidiens : version gratuite d'abord, pendant un mois",
            "Usage intensif (chaque jour, documents longs) : abonnement forfaitaire, 20 euros par mois environ",
            "Automatisations (relances, devis automatiques) : offre pro à la consommation, coût souvent de quelques euros par mois à votre échelle",
        ]),
        callout_info("Repère : si l'IA vous fait gagner 5 heures par semaine valorisées 30 euros l'heure, un abonnement à 20 euros par mois se rembourse en 40 minutes."),
     ),
    },
    {
     "title": "Les limites à connaître avant de promettre",
     "image_query": "hourglass sand time",
     "build": lambda img: doc(
        heading(1, "Les limites à connaître avant de promettre"),
        para("L'IA a des limites stables qu'il faut connaître pour ne pas surpromettre à vos clients ou à votre équipe."),
        image(img),
        bullets([
            "Mémoire : chaque conversation repart de zéro, sauf fonction « projet » ou « mémoire » activée",
            "Fraîcheur : sans fonction de recherche web, ses connaissances s'arrêtent à sa date d'entraînement",
            "Volume : les documents très longs (plusieurs centaines de pages) demandent des outils adaptés",
            "Chiffres : elle calcule de façon fiable sur du court texte, mais toute donnée critique se vérifie",
        ]),
        para("Ces limites ne sont pas des défauts rédhibitoires : ce sont les contours de l'outil. Un marteau ne visse pas ; une IA ne remplace pas votre expert-comptable."),
     ),
    },
    {
     "title": "Quiz : coûts et limites",
     "build": lambda img: doc(
        heading(1, "Quiz : coûts et limites"),
        quiz_node([
            {"q": "Qu'est-ce qu'un token ?",
             "answers": [{"a": "Une monnaie crypto", "c": False},
                        {"a": "Une unité de texte, environ 3 quarts de mot", "c": True},
                        {"a": "Un jeton de casino", "c": False},
                        {"a": "Une prise électrique", "c": False}]},
            {"q": "Quelle offre pour commencer sans risque ?",
             "answers": [{"a": "La version gratuite pendant un mois", "c": True},
                        {"a": "L'abonnement le plus cher direct", "c": False},
                        {"a": "Aucune, c'est interdit", "c": False},
                        {"a": "Un abonnement pour chaque employé", "c": False}]},
            {"q": "Que fait l'assistant à la fin d'une conversation ?",
             "answers": [{"a": "Il oublie tout (sauf mémoire/projet activés)", "c": True},
                        {"a": "Il se souvient de tout pour toujours", "c": False},
                        {"a": "Il envoie un email", "c": False},
                        {"a": "Il s'améliore grâce à vous uniquement", "c": False}]},
            {"q": "Sans recherche web, que sait l'assistant des actualités récentes ?",
             "answers": [{"a": "Tout", "c": False},
                        {"a": "Rien de plus récent que sa date d'entraînement", "c": True},
                        {"a": "Uniquement le sport", "c": False},
                        {"a": "Ça dépend de la météo", "c": False}]},
            {"q": "Comment justifier un abonnement payant ?",
             "answers": [{"a": "En calculant le temps gagné et sa valeur", "c": True},
                        {"a": "En le demandant poliment", "c": False},
                        {"a": "Il n'y a rien à justifier", "c": False},
                        {"a": "En changeant de métier", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
# ═══════════════ PARCOURS 2 : L'ART DU PROMPT ═══════════════
{
 "slug": "premier-prompt-efficace",
 "title": "Écrire son premier prompt efficace",
 "level": "Débutant",
 "description": "La méthode des 3 C (Contexte, Consigne, Contraintes) pour obtenir du premier coup ce que vous voulez : un devis bien rédigé, une relance polie, une annonce qui vend. Avec les formulations prêtes à copier.",
 "learnings": "Structurer une demande en 3 blocs, obtenir la bonne réponse dès le premier essai, corriger une réponse décevante, constituer ses premières formulations réutilisables",
 "tags": "ia, débutant, parcours-prompt, redaction, methode",
 "cover_query": "writing notebook pen",
 "chapters": [
  {
   "title": "La méthode des 3 C",
   "description": "La structure d'un prompt qui marche à chaque fois.",
   "activities": [
    {
     "title": "Contexte, Consigne, Contraintes",
     "image_query": "carpenter measuring wood",
     "build": lambda img: doc(
        heading(1, "Contexte, Consigne, Contraintes"),
        para("Un bon prompt, c'est comme un bon brief d'apprenti : il dit qui vous êtes, ce que vous voulez, et sous quelle forme. Trois blocs suffisent."),
        image(img),
        heading(2, "Bloc 1 : le Contexte (qui, quoi, pour qui)"),
        para("« Tu es assistant d'un électricien indépendant à Nantes. Je viens d'intaller un tableau électrique chez un particulier. » L'IA cesse d'être générique dès qu'elle sait pour qui elle travaille."),
        heading(2, "Bloc 2 : la Consigne (la tâche précise)"),
        para("« Rédige la facture correspondante : main d'oeuvre 3 heures à 45 euros, matériel 180 euros, TVA 20 %. »"),
        heading(2, "Bloc 3 : les Contraintes (forme, ton, longueur)"),
        para("« Ton professionnel et chaleureux, une page maximum, avec mention de la garantie décennale. »"),
        callout_info("Testez : refaites une demande que l'IA avait mal traitée cette semaine, en ajoutant les 3 C. Comparez."),
     ),
    },
    {
     "title": "Corriger une réponse décevante",
     "image_query": "teacher whiteboard",
     "build": lambda img: doc(
        heading(1, "Corriger une réponse décevante"),
        para("Une réponse moyenne n'est pas un échec : c'est la moitié du chemin. On corrige comme avec un collaborateur, par instructions courtes."),
        image(img),
        ordered([
            "Précisez ce qui cloque : « trop long », « trop commercial », « le paragraphe 2 est faux »",
            "Donnez un exemple de ce que vous voulez, même approximatif",
            "Demandez une variante : « même chose, 3 fois plus court »",
            "Changez d'angle : « réécris comme si tu parlais à un client pressé »",
        ]),
        callout_warning("Piège : reformuler TOUTE la demande à chaque fois. L'assistant garde le fil de la conversation : corrigez point par point, c'est plus rapide et plus précis."),
     ),
    },
    {
     "title": "Quiz : la méthode des 3 C",
     "build": lambda img: doc(
        heading(1, "Quiz : la méthode des 3 C"),
        quiz_node([
            {"q": "Que signifie « 3 C » ?",
             "answers": [{"a": "Contexte, Consigne, Contraintes", "c": True},
                        {"a": "Calcul, Copie, Collage", "c": False},
                        {"a": "Client, Commercial, Comptable", "c": False},
                        {"a": "Cours, Corrigé, Classement", "c": False}]},
            {"q": "Que contient le bloc Contexte ?",
             "answers": [{"a": "Qui vous êtes et pour qui vous travaillez", "c": True},
                        {"a": "Votre code bancaire", "c": False},
                        {"a": "La météo", "c": False},
                        {"a": "Un poème", "c": False}]},
            {"q": "Réponse trop longue : quelle correction efficace ?",
             "answers": [{"a": "Reformuler toute la demande depuis le début", "c": False},
                        {"a": "« même chose, 3 fois plus court »", "c": True},
                        {"a": "Tout supprimer et abandonner", "c": False},
                        {"a": "Écrire en majuscules", "c": False}]},
            {"q": "Pourquoi donner un exemple dans la demande ?",
             "answers": [{"a": "Pour allonger le message", "c": False},
                        {"a": "Parce que l'exemple guide la prédiction vers le style attendu", "c": True},
                        {"a": "Par politesse", "c": False},
                        {"a": "Pour tester la patience de l'IA", "c": False}]},
            {"q": "L'assistant garde-t-il le fil de la conversation ?",
             "answers": [{"a": "Non, chaque message est indépendant", "c": False},
                        {"a": "Oui, on peut donc corriger point par point", "c": True},
                        {"a": "Seulement le lundi", "c": False},
                        {"a": "Uniquement par email", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "contexte-metier-prompt",
 "title": "Donner le contexte métier : la clé des réponses sur mesure",
 "level": "Débutant",
 "description": "Ce qui différencie une réponse générique d'une réponse qui vous ressemble : le contexte. Apprenez à préparer votre « fiche métier » à coller en début de conversation pour des résultats immédiatement personnalisés.",
 "learnings": "Construire sa fiche métier réutilisable, adapter le ton au destinataire, transformer un prompt générique en prompt métier, sauvegarder ses contextes",
 "tags": "ia, débutant, parcours-prompt, contexte, personnalisation",
 "cover_query": "toolbox workshop organized",
 "chapters": [
  {
   "title": "Votre fiche métier réutilisable",
   "description": "Le bloc de contexte qui change tout, à préparer une fois.",
   "activities": [
    {
     "title": "Construire la fiche métier en 10 minutes",
     "image_query": "index cards organization",
     "build": lambda img: doc(
        heading(1, "Construire la fiche métier en 10 minutes"),
        para("Au lieu de réexpliquer votre activité à chaque conversation, préparez une fiche de 10 lignes dans vos notes. Vous la collerez au début de chaque session : c'est l'équivalent d'un brief d'intérimaire qui, lui, ne repart jamais à zéro."),
        image(img),
        heading(2, "Le contenu type"),
        ordered([
            "Métier et zone : « électricien, Nantes et sud-Loire »",
            "Clients type : « particuliers 60 %, petites entreprises 40 % »",
            "Tarifs de référence : taux horaire, forfaits courants",
            "Ton de marque : « direct, rassurant, sans jargon »",
            "Règles maison : « toujours mentionner la garantie, toujours proposer un créneau sous 48 h »",
        ]),
        para("Résultat : chaque réponse arrive déjà calibrée. Vous ne reprenez plus que les détails du cas."),
        callout_info("Astuce Ordria : gardez la fiche dans une note téléphone intitulée « contexte IA ». Copier-coller prend 4 secondes et économise 4 ajustements."),
     ),
    },
    {
     "title": "Adapter le ton au destinataire",
     "image_query": "conversation people cafe",
     "build": lambda img: doc(
        heading(1, "Adapter le ton au destinataire"),
        para("Même information, trois tons : à un client fidèle on ajoute une touche personnelle, à un nouveau client on rassure avec des références, à un fournisseur on reste factuel. L'IA switch très bien si vous le demandez explicitement."),
        image(img),
        bullets([
            "« Réécris ce message pour un client fidèle de 5 ans »",
            "« Version pour un prospect qui compare trois devis »",
            "« Version SMS, 160 caractères maximum »",
            "« Version pour un client mécontent : calme, responsable, orienté solution »",
        ]),
        callout_warning("Piège : laisser l'IA choisir le ton seule. Par défaut elle produit un ton commercial standard qui peut sonner faux dans votre métier. Le ton, c'est vous qui le donnez."),
     ),
    },
   ],
  },
 ],
},
]
