# -*- coding: utf-8 -*-
"""Catalogue D - Parcours 5 « IA au bureau » (4 cours) + Parcours 6
« Déployer l'IA dans son entreprise » (3 cours avancé).
Ton Ordria, aucun em dash."""
from factory import (doc, heading, para, bullets, ordered, callout_info,
                     callout_warning, image, quiz_node)

COURSES = [
# ═══════════════ PARCOURS 5 : IA AU BUREAU ═══════════════
{
 "slug": "tableurs-calculs-ia",
 "title": "Tableurs et calculs avec l'IA : Excel et Sheets",
 "level": "Intermédiaire",
 "description": "Extraire, croiser, calculer : l'IA transforme vos tableaux bruts en réponses. Formules expliquées, tableaux croisés préparés, erreurs détectées : le tableur redevient un outil, pas un ennemi.",
 "learnings": "Faire analyser un tableau par l'IA, obtenir les bonnes formules expliquées, détecter les erreurs d'un tableau, croiser des données sans être analyste",
 "tags": "ia, intermédiaire, parcours-bureau, excel, tableur, calculs",
 "cover_query": "spreadsheet excel laptop work",
 "chapters": [
  {
   "title": "Le tableau qui répond aux questions",
   "description": "De la donnée brute à la décision.",
   "activities": [
    {
     "title": "Faire analyser un tableau",
     "image_query": "data analysis charts desk",
     "build": lambda img: doc(
        heading(1, "Faire analyser un tableau"),
        para("Copier-coller un tableau dans un assistant IA (en anonymisant) et poser des questions en français : c'est le niveau d'usage qui change tout. L'IA compte, trie, croise et repère les anomalies."),
        image(img),
        heading(2, "Les questions qui marchent"),
        ordered([
            "« Résume ce tableau : lignes, colonnes, période couverte, anomalies visibles »",
            "« Quel client représente le plus gros chiffre d'affaires ? Et la plus longue durée de paiement ? »",
            "« Compare ces deux mois : 3 évolutions notables »",
            "« Repère les doublons et les incohérences (totaux, dates, montants négatifs suspects) »",
        ]),
        callout_info("Règle d'or : vérifiez toujours le total général après analyse. Si l'IA le retrouve correctement, l'extraction est fiable ; sinon, redonnez le tableau plus proprement."),
     ),
    },
    {
     "title": "Les formules enfin expliquées",
     "image_query": "keyboard typing work office",
     "build": lambda img: doc(
        heading(1, "Les formules enfin expliquées"),
        para("RECHERCHEV, SOMME.SI, NB.SI : des noms qui font fuir. L'IA inverse la logique : vous décrivez ce que vous VOULEZ, elle écrit la formule ET l'explique en français."),
        image(img),
        ordered([
            "Décrivez : « dans la colonne D, je veux le total des ventes de la colonne C uniquement pour le commercial Pierre »",
            "L'IA donne la formule : SOMME.SI avec les arguments expliqués ligne par ligne",
            "En cas d'erreur : collez le message d'erreur et votre formule, l'IA diagnostique",
            "Documentez : « résume cette formule en une phrase à garder dans mes notes »",
        ]),
        callout_warning("Attention aux tableaux confidentiels : anonymisez les noms avant de coller (client A, B, C). Les montants suffisent pour 95 % des analyses."),
     ),
    },
    {
     "title": "Quiz : tableurs",
     "build": lambda img: doc(
        heading(1, "Quiz : tableurs"),
        quiz_node([
            {"q": "Que faire avant de coller un tableau confidentiel ?",
             "answers": [{"a": "Anonymiser les noms", "c": True},
                        {"a": "Le traduire en anglais", "c": False},
                        {"a": "Le mettre en gras", "c": False},
                        {"a": "Rien", "c": False}]},
            {"q": "Comment vérifier qu'une analyse IA est fiable ?",
             "answers": [{"a": "Vérifier le total général", "c": True},
                        {"a": "Y croire", "c": False},
                        {"a": "Recommencer 10 fois", "c": False},
                        {"a": "Impossible", "c": False}]},
            {"q": "Comment obtenir une formule de l'IA ?",
             "answers": [{"a": "Décrire en français ce qu'on veut obtenir", "c": True},
                        {"a": "Donner le nom de la formule", "c": False},
                        {"a": "Écrire en morse", "c": False},
                        {"a": "Payer plus cher", "c": False}]},
            {"q": "Que faire d'un message d'erreur Excel ?",
             "answers": [{"a": "Le coller à l'IA avec la formule pour diagnostic", "c": True},
                        {"a": "Effacer tout", "c": False},
                        {"a": "Redémarrer l'ordinateur", "c": False},
                        {"a": "Pleurer", "c": False}]},
            {"q": "Quel usage typique des tableaux croisés avec l'IA ?",
             "answers": [{"a": "Croiser des données sans être analyste", "c": True},
                        {"a": "Faire des dessins", "c": False},
                        {"a": "Changer la météo", "c": False},
                        {"a": "Aucun", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "presentations-supports-ia",
 "title": "Présentations et supports visuels avec l'IA",
 "level": "Intermédiaire",
 "description": "Une présentation client demain matin ? L'IA structure le propos, propose le déroulé slide par slide, rédige les contenus et suggère les visuels. Vous gardez le fond et la voix, l'outil fait la mécanique.",
 "learnings": "Structurer une présentation persuasive, obtenir un déroulé complet par diapositive, rédiger contenus et notes d'intervenant, choisir les visuels adaptés",
 "tags": "ia, intermédiaire, parcours-bureau, presentation, powerpoint, visuel",
 "cover_query": "presentation meeting screen",
 "chapters": [
  {
   "title": "De l'idée au déroulé",
   "description": "La structure avant les couleurs.",
   "activities": [
    {
     "title": "Structurer une présentation qui convainc",
     "image_query": "sticky notes brainstorming wall",
     "build": lambda img: doc(
        heading(1, "Structurer une présentation qui convainc"),
        para("Une présentation qui convainc suit rarement l'ordre de vos dossiers : elle suit le raisonnement du public. L'IA est excellente pour imposer cette discipline."),
        image(img),
        heading(2, "La structure qui marche en clientèle"),
        ordered([
            "Situation : ce que vit le client (ses mots, pas les vôtres)",
            "Problème : ce que ça lui coûte (temps, argent, risque)",
            "Solution : ce que vous proposez, en une phrase",
            "Preuve : cas concret, chiffres, démonstration",
            "Prochain pas : une action simple, datée",
        ]),
        para("Demandez : « structure ce propos en 8 diapositives selon la structure situation/problème/solution/preuve/prochain pas, avec titre et 3 puces maximum par diapositive, plus les notes de ce que je dois dire »."),
        callout_info("La règle des 3 puces n'est pas de l'esthétisme : c'est ce que le public retient. Ce qui n'est pas dit à l'oral n'a pas à surcharger la diapositive : ça va dans les notes."),
     ),
    },
    {
     "title": "Visuels et mise en forme sans designer",
     "image_query": "design colors palette creative",
     "build": lambda img: doc(
        heading(1, "Visuels et mise en forme sans designer"),
        para("L'IA rédige, suggère les visuels à chercher (banques d'images libres) et décrit la mise en page. Certaines suites bureautiques génèrent même la présentation complète à partir du plan."),
        image(img),
        ordered([
            "Le plan validé : une idée par diapositive, 3 puces maximum",
            "« Pour chaque diapositive, suggère le type de visuel : photo, schéma, chiffre clé, citation »",
            "Notes d'intervenant rédigées : vous savez quoi dire, pas quoi lire",
            "Relecture à voix haute : la présentation doit se défendre SANS diapositives",
        ]),
        callout_warning("Le piège de la présentation générée d'un bloc : 15 diapositives denses et génériques. Repartez toujours de VOTRE cas client : l'IA embellit un propos, elle ne le remplace pas."),
     ),
    },
    {
     "title": "Quiz : présentations",
     "build": lambda img: doc(
        heading(1, "Quiz : présentations"),
        quiz_node([
            {"q": "Quel ordre pour une présentation client ?",
             "answers": [{"a": "Situation, problème, solution, preuve, prochain pas", "c": True},
                        {"a": "Plan comptable, annexes, texte legal", "c": False},
                        {"a": "Alphabétique", "c": False},
                        {"a": "Au hasard", "c": False}]},
            {"q": "Combien de puces par diapositive ?",
             "answers": [{"a": "3 maximum", "c": True},
                        {"a": "15", "c": False},
                        {"a": "30", "c": False},
                        {"a": "Aucune", "c": False}]},
            {"q": "Où va le détail non dit à l'oral ?",
             "answers": [{"a": "Dans les notes d'intervenant", "c": True},
                        {"a": "Sur la diapositive", "c": False},
                        {"a": "Nulle part", "c": False},
                        {"a": "Dans un email après", "c": False}]},
            {"q": "Le piège de la présentation générée d'un bloc ?",
             "answers": [{"a": "Générique et dense : il faut repartir de son cas client", "c": True},
                        {"a": "Trop courte", "c": False},
                        {"a": "Mal orthographiée", "c": False},
                        {"a": "Aucun piège", "c": False}]},
            {"q": "Que doit supporter une bonne présentation ?",
             "answers": [{"a": "Elle doit se défendre sans diapositives", "c": True},
                        {"a": "Rien", "c": False},
                        {"a": "Le poids du projecteur", "c": False},
                        {"a": "Une coupure de courant", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "visuels-images-pro",
 "title": "Créer des visuels et images professionnels",
 "level": "Intermédiaire",
 "description": "Images pour le site, photos d'ambiance pour les réseaux, illustrations de documents : les générateurs d'images et banques libres, bien utilisés, habillent votre communication sans budget agence.",
 "learnings": "Écrire un prompt d'image efficace, distinguer génération et banques de photos libres, respecter les droits d'usage, intégrer des visuels cohérents dans sa communication",
 "tags": "ia, intermédiaire, parcours-bureau, images, visuel, communication",
 "cover_query": "photography camera studio light",
 "chapters": [
  {
   "title": "Le prompt d'image qui donne le bon résultat",
   "description": "Décrire une image comme un brief photographe.",
   "activities": [
    {
     "title": "La recette du prompt d'image",
     "image_query": "art paint colors creative",
     "build": lambda img: doc(
        heading(1, "La recette du prompt d'image"),
        para("Un générateur d'images suit un brief en 5 ingrédients : sujet, style, cadrage, lumière, ambiance. L'ordre et la précision comptent plus que la longueur."),
        image(img),
        ordered([
            "Sujet : « un menuisier dans son atelier »",
            "Action et détail : « ponçant une table en chêne, copeaux visibles »",
            "Style : « photographie professionnelle, style éditorial »",
            "Cadrage et lumière : « plan moyen, lumière naturelle douce d'atelier »",
            "Ambiance : « calme, artisanat, authenticité »",
        ]),
        para("La même logique vaut pour chercher en banque d'images : c'est la DESCRIPTION qui trouve l'image, pas le mot-clé isolé."),
        callout_info("Pour les usages professionnels courants (site, réseaux, documents), les banques de photos libres de droits comme Pexels ou Unsplash couvrent l'essentiel. La génération IA sert les cas spécifiques : votre atelier vu d'un angle impossible, une illustration d'un concept abstrait."),
     ),
    },
    {
     "title": "Droits, cohérence et bonnes pratiques",
     "image_query": "brand guidelines design consistency",
     "build": lambda img: doc(
        heading(1, "Droits, cohérence et bonnes pratiques"),
        para("Un visuel professionnel est un visuel dont vous avez le droit d'usage et qui respecte votre identité. Trois réflexes suffisent."),
        image(img),
        bullets([
            "Droits : vérifiez la licence de chaque image (libre pour usage commercial ou pas) et gardez la source notée",
            "Crédit : quand le photographe le demande, créditez : c'est gratuit et c'est la règle de la maison pour les banques communautaires",
            "Cohérence : mêmes tons, même style sur tout un support ; demandez à l'IA de décrire votre charte visuelle en mots-clés réutilisables",
        ]),
        callout_warning("Ne générez ni ne publiez jamais de visuel représentant des personnes réelles identifiables ou des marques déposées sans droit. Pour vos clients et votre équipe : photos réelles avec accord, toujours."),
     ),
    },
    {
     "title": "Quiz : visuels",
     "build": lambda img: doc(
        heading(1, "Quiz : visuels"),
        quiz_node([
            {"q": "Les 5 ingrédients d'un prompt d'image ?",
             "answers": [{"a": "Sujet, action, style, cadrage/lumière, ambiance", "c": True},
                        {"a": "Prix, taille, poids, couleur, date", "c": False},
                        {"a": "Un seul mot-clé", "c": False},
                        {"a": "Une recette de cuisine", "c": False}]},
            {"q": "Pour les usages courants, que privilégier ?",
             "answers": [{"a": "Les banques libres de droits (Pexels, Unsplash)", "c": True},
                        {"a": "Les images volées sur Google", "c": False},
                        {"a": "Les dessins de children", "c": False},
                        {"a": "Aucune image", "c": False}]},
            {"q": "Que faire quand le photographe demande un crédit ?",
             "answers": [{"a": "Créditer : gratuit et conforme", "c": True},
                        {"a": "Ignorer", "c": False},
                        {"a": "Recadrer l'image", "c": False},
                        {"a": "Payer double", "c": False}]},
            {"q": "Comment assurer la cohérence visuelle ?",
             "answers": [{"a": "Mêmes tons et même style, charte décrite en mots-clés", "c": True},
                        {"a": "Tout en noir et blanc aléatoirement", "c": False},
                        {"a": "Un style par page", "c": False},
                        {"a": "C'est impossible", "c": False}]},
            {"q": "Que ne jamais générer ni publier ?",
             "answers": [{"a": "Des personnes réelles identifiables ou des marques sans droit", "c": True},
                        {"a": "Des photos de paysages", "c": False},
                        {"a": "Des illustrations abstraites", "c": False},
                        {"a": "Des icônes", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "resumer-traduire-adapter",
 "title": "Résumer, traduire, adapter : documents de tous formats",
 "level": "Intermédiaire",
 "description": "Un appel d'offres de 40 pages, une notice en anglais, un rapport à adapter pour un client pressé : l'IA avale les documents longs et rend l'essentiel, dans la langue et le format voulu.",
 "learnings": "Résumer un document long sans perdre l'essentiel, traduire en gardant le ton, adapter un même contenu à plusieurs formats, extraire les données clés d'un document",
 "tags": "ia, intermédiaire, parcours-bureau, resume, traduction, documents",
 "cover_query": "documents reading glasses desk",
 "chapters": [
  {
   "title": "Le document long dompté",
   "description": "Résumé utile, extraction ciblée, adaptation.",
   "activities": [
    {
     "title": "Résumer sans trahir",
     "image_query": "reading book pages",
     "build": lambda img: doc(
        heading(1, "Résumer sans trahir"),
        para("Un mauvais résumé coupe ce qui dérange et garde ce qui brille. La méthode en deux temps garantit un résumé fidèle : d'abord la structure, ensuite le détail voulu."),
        image(img),
        ordered([
            "« Donne le plan de ce document : sections et message de chacune en une ligne »",
            "« Résume en 10 lignes pour un décideur pressé : décisions à prendre, échéances, risques »",
            "« Liste tout ce qui concerne [mon sujet précis] dans ce document »",
            "« Quelles informations ce document NE donne-t-il pas et que je devrais vérifier ailleurs ? »",
        ]),
        callout_info("La dernière question est la plus rentable : elle révèle les angles morts du document avant que votre interlocuteur ne les pointe."),
     ),
    },
    {
     "title": "Traduire et adapter sans trahir le ton",
     "image_query": "languages translation dictionary",
     "build": lambda img: doc(
        heading(1, "Traduire et adapter sans trahir le ton"),
        para("L'IA traduit remarquablement bien le sens ; le ton et les usages locaux demandent une consigne explicite. La règle : dire POUR QUI et POURQUOI."),
        image(img),
        ordered([
            "« Traduis en anglais pour un client professionnel américain : direct, sans littéralisme français »",
            "« Adapte ce document pour un particulier : retire le jargon, ajoute une explication simple par terme technique »",
            "« Même contenu en version WhatsApp : messages courts, ton spontané »",
        ]),
        callout_warning("Vocabulaire technique et juridique : donnez à l'IA VOS références (termes officiels, traductions maison) sinon elle choisira des équivalents approximatifs. En cas d'enjeu contractuel : validation par un traducteur ou jurilinguiste."),
     ),
    },
    {
     "title": "Quiz : résumer et traduire",
     "build": lambda img: doc(
        heading(1, "Quiz : résumer et traduire"),
        quiz_node([
            {"q": "Première étape pour résumer un long document ?",
             "answers": [{"a": "Demander son plan, section par section", "c": True},
                        {"a": "Lire le dernier paragraphe", "c": False},
                        {"a": "Le traduire", "c": False},
                        {"a": "Le photocopier", "c": False}]},
            {"q": "La question la plus rentable sur un document ?",
             "answers": [{"a": "« Quelles informations ce document NE donne-t-il pas ? »", "c": True},
                        {"a": "« Qui l'a écrit ? »", "c": False},
                        {"a": "« Combien de pages ? »", "c": False},
                        {"a": "« Quelle couleur de couverture ? »", "c": False}]},
            {"q": "Que préciser pour une bonne traduction IA ?",
             "answers": [{"a": "Pour qui et pourquoi : ton et usages visés", "c": True},
                        {"a": "L'heure de la traduction", "c": False},
                        {"a": "Rien", "c": False},
                        {"a": "La météo", "c": False}]},
            {"q": "Que faire des termes techniques maison ?",
             "answers": [{"a": "Donner ses références à l'IA", "c": True},
                        {"a": "La laisser choisir", "c": False},
                        {"a": "Les supprimer", "c": False},
                        {"a": "Les traduire en latin", "c": False}]},
            {"q": "Enjeu contractuel : qui valide la traduction ?",
             "answers": [{"a": "Un traducteur ou jurilinguiste", "c": True},
                        {"a": "Personne", "c": False},
                        {"a": "Le client", "c": False},
                        {"a": "L'IA seule", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
# ═══════════════ PARCOURS 6 : DÉPLOYER L'IA EN ENTREPRISE ═══════════════
{
 "slug": "automatiser-chaine-complete",
 "title": "Automatiser une chaîne complète : du déclencheur au résultat",
 "level": "Avancé",
 "description": "Cours avancé : passer de « l'IA m'aide » à « la chaîne tourne seule ». Anatomie d'une automatisation : déclencheur, étapes, points de contrôle humains. Conçu pour comprendre puis piloter ce qu'Ordria déploie chez ses clients.",
 "learnings": "Découper un processus en étapes automatisables, identifier les points de contrôle humains, comprendre les outils de chaînage, chiffrer le gain d'une automatisation",
 "tags": "ia, avancé, parcours-deploiement, automatisation, processus",
 "cover_query": "gears machinery mechanism industrial",
 "chapters": [
  {
   "title": "L'anatomie d'une automatisation",
   "description": "Toute chaîne suit la même logique : apprendre à la lire.",
   "activities": [
    {
     "title": "Déclencheur, étapes, contrôle humain",
     "image_query": "conveyor belt factory automation",
     "build": lambda img: doc(
        heading(1, "Déclencheur, étapes, contrôle humain"),
        para("Une automatisation fiable se lit comme une recette : un événement déclenche, des étapes s'enchaînent, un humain contrôle aux bons endroits. Ni plus, ni moins."),
        image(img),
        heading(2, "Exemple : la relance de facture automatisée"),
        ordered([
            "Déclencheur : facture échue non payée depuis 15 jours (la DATE, pas la mémoire)",
            "Étape 1 : le système lit la facture et le client concerné",
            "Étape 2 : l'IA rédige la relance niveau 1 avec l'historique du client",
            "Contrôle : le message part automatiquement SEULEMENT si le client est fiable ; sinon, brouillon pour validation",
            "Étape 3 : si paiement reçu, la chaîne s'arrête ; sinon, niveau 2 programmé à J+35",
        ]),
        para("Cette lecture en 5 lignes est le langage commun entre vous et tout prestataire (y compris Ordria) : elle permet de spécifier, comprendre et auditer ce qui tourne."),
        callout_info("Le contrôle humain bien placé vaut mieux que la surveillance permanente : une validation au bon point de la chaîne sécurise tout le reste."),
     ),
    },
    {
     "title": "Chiffrer avant d'automatiser",
     "image_query": "abacus counting calculation",
     "build": lambda img: doc(
        heading(1, "Chiffrer avant d'automatiser"),
        para("Tout ne mérite pas d'être automatisé. La règle des 3 dimensions : fréquence, temps unitaire, risque. Automatisez ce qui est fréquent, long et à faible risque de jugement."),
        image(img),
        ordered([
            "Listez le processus et ses étapes réelles (observées, pas théoriques)",
            "Mesurez : combien de fois par mois, combien de minutes à chaque fois",
            "Classez chaque étape : mécanique (automatisable) ou jugeable (humain)",
            "Chiffrez : temps récupéré par mois, valorisé à votre taux horaire réel",
        ]),
        callout_warning("L'erreur classique : automatiser d'abord le processus le plus ANORMAL, par agacement. Automatisez le processus fréquent et stable : une chaîne bâtie sur un processus bancal industrialise le désordre."),
     ),
    },
    {
     "title": "Quiz : chaînes d'automatisation",
     "build": lambda img: doc(
        heading(1, "Quiz : chaînes d'automatisation"),
        quiz_node([
            {"q": "Qu'est-ce qu'un déclencheur fiable ?",
             "answers": [{"a": "Un événement daté, jamais la mémoire", "c": True},
                        {"a": "Une envie subite", "c": False},
                        {"a": "Un post-it", "c": False},
                        {"a": "Le vendredi soir", "c": False}]},
            {"q": "Où placer le contrôle humain dans une chaîne ?",
             "answers": [{"a": "Au bon point : une validation bien placée sécurise le reste", "c": True},
                        {"a": "Partout, en permanence", "c": False},
                        {"a": "Nulle part", "c": False},
                        {"a": "À la fin seulement, toujours", "c": False}]},
            {"q": "Quelles dimensions pour prioriser une automatisation ?",
             "answers": [{"a": "Fréquence, temps unitaire, risque", "c": True},
                        {"a": "Couleur, taille, poids", "c": False},
                        {"a": "Humeur, météo, horoscope", "c": False},
                        {"a": "Une seule : le prix", "c": False}]},
            {"q": "Quelle étape n'est PAS automatisable ?",
             "answers": [{"a": "Celle qui exige un jugement humain", "c": True},
                        {"a": "Celle qui se répète", "c": False},
                        {"a": "Celle qui est chronométrée", "c": False},
                        {"a": "Celle qui produit un email", "c": False}]},
            {"q": "Que fait-on d'un processus bancal ?",
             "answers": [{"a": "On le stabilise AVANT d'automatiser", "c": True},
                        {"a": "On l'automatise tel quel", "c": False},
                        {"a": "On l'oublie", "c": False},
                        {"a": "On double la bande passante", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "charte-ia-referent",
 "title": "Charte IA et référent : encadrer l'usage en équipe",
 "level": "Avancé",
 "description": "L'IA en entreprise s'encadre : qui peut utiliser quoi, quelles données, quelle validation. Ce cours construit votre charte IA en une page et prépare le rôle de référent IA, comme l'exige la formule Expertise d'Ordria.",
 "learnings": "Rédiger une charte IA d'une page utile, désigner et outiller un référent IA, former l'équipe sans la brider, se préparer aux obligations de transparence",
 "tags": "ia, avancé, parcours-deploiement, charte, rgpd, equipe, gouvernance",
 "cover_query": "team meeting office discussion",
 "chapters": [
  {
   "title": "La charte en une page",
   "description": "Un cadre simple que tout le monde lit et applique.",
   "activities": [
    {
     "title": "Les 6 blocs d'une charte utile",
     "image_query": "contract document signing pen",
     "build": lambda img: doc(
        heading(1, "Les 6 blocs d'une charte utile"),
        para("Une charte IA de 12 pages ne sera jamais lue. La version une page, affichée et appliquée, protège réellement l'entreprise. Six blocs suffisent."),
        image(img),
        ordered([
            "Outils autorisés : lesquels, quelles versions, qui les installe",
            "Données : ce qui peut être traité, ce qui doit être anonymisé, ce qui est interdit",
            "Validation : quels documents sortent sans relecture, lesquels exigent validation du référent",
            "Transparence : quand dire au client qu'un contenu est assisté par IA",
            "Formation : qui forme les nouveaux, quand, sur quoi",
            "Incidents : quoi faire en cas d'erreur ou de fuite (qui prévenir, dans quel délai)",
        ]),
        para("Demandez à l'IA de préparer votre premier jet à partir de ces 6 blocs et de VOS règles maison, puis validez en équipe : une charte co-écrite est une charte appliquée."),
        callout_info("La charte d'Ordria tient sur une page A4 et accompagne chacun de ses déploiements. C'est aussi ce que réclament de plus en plus les grands clients de ses clients : avoir une charte devient un argument commercial."),
     ),
    },
    {
     "title": "Le référent IA : le phare de l'équipe",
     "image_query": "lighthouse coast light",
     "build": lambda img: doc(
        heading(1, "Le référent IA : le phare de l'équipe"),
        para("Le référent IA n'est pas l'informaticien : c'est le collègue qui connaît les usages, tient la charte et répond aux questions. Dans une TPE, c'est souvent le gérant ou un collaborateur pionnier."),
        image(img),
        bullets([
            "Rôle : valider les nouveaux usages, tenir la bibliothèque de gabarits, arbitrer les cas limites",
            "Outillage : gabarits à jour, veille légère, contact prestataire",
            "Rituel : 30 minutes par mois en équipe : ce qui marche, ce qui bloque, une nouveauté utile",
            "Signal faible à surveiller : les usages shadow (collègues utilisant des outils non autorisés) : les comprendre avant de les interdire",
        ]),
        callout_warning("La charte qui punit échoue : si l'équipe contourne, c'est que la règle est irréaliste ou l'outil autorisé insuffisant. Le référent ajuste le cadre autant que les comportements."),
     ),
    },
    {
     "title": "Quiz : charte et référent",
     "build": lambda img: doc(
        heading(1, "Quiz : charte et référent"),
        quiz_node([
            {"q": "Quelle longueur pour une charte IA appliquée ?",
             "answers": [{"a": "Une page", "c": True},
                        {"a": "80 pages", "c": False},
                        {"a": "Un roman", "c": False},
                        {"a": "Aucune charte", "c": False}]},
            {"q": "Qui est le référent IA typique en TPE ?",
             "answers": [{"a": "Le gérant ou un collaborateur pionnier", "c": True},
                        {"a": "Un avocat externe", "c": False},
                        {"a": "Personne", "c": False},
                        {"a": "Le fournisseur d'électricité", "c": False}]},
            {"q": "Que faire des usages shadow (outils non autorisés) ?",
             "answers": [{"a": "Les comprendre avant de les interdire", "c": True},
                        {"a": "Licencier immédiatement", "c": False},
                        {"a": "Les ignorer", "c": False},
                        {"a": "Tout interdire", "c": False}]},
            {"q": "Quel rituel d'équipe recommandé ?",
             "answers": [{"a": "30 minutes par mois : usages, blocages, nouveautés", "c": True},
                        {"a": "Une réunion quotidienne de 3 heures", "c": False},
                        {"a": "Aucun", "c": False},
                        {"a": "Un sondage annuel", "c": False}]},
            {"q": "Pourquoi une charte devient-elle un argument commercial ?",
             "answers": [{"a": "Les grands clients la réclament de plus en plus", "c": True},
                        {"a": "Elle est jolie", "c": False},
                        {"a": "Elle coûte cher", "c": False},
                        {"a": "Elle est obligatoire depuis 1804", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "plan-deploiement-30-jours",
 "title": "Plan de déploiement 30 jours : le projet fil rouge",
 "level": "Avancé",
 "description": "Le cours de synthèse : transformer tout ce que vous avez appris en un plan de 30 jours, semaine par semaine, avec indicateurs de réussite. La méthode utilisée dans la formule Expertise d'Ordria, appliquée à votre entreprise.",
 "learnings": "Choisir son projet fil rouge, bâtir un plan 30 jours réaliste, mesurer les gains obtenus, pérenniser les pratiques au-delà du mois",
 "tags": "ia, avancé, parcours-deploiement, projet, plan, synthese",
 "cover_query": "road path horizon journey",
 "chapters": [
  {
   "title": "Le fil rouge et le plan",
   "description": "Un projet réel, quatre semaines, des résultats mesurés.",
   "activities": [
    {
     "title": "Semaines 1 et 2 : socle et premier gain",
     "image_query": "beginning start line race",
     "build": lambda img: doc(
        heading(1, "Semaines 1 et 2 : socle et premier gain"),
        para("Le plan 30 jours démarre par un choix discipliné : UN processus fil rouge (fréquent, mesurable, à faible risque) et une équipe de deux personnes motivées. Pas plus."),
        image(img),
        heading(2, "Semaine 1 : le socle"),
        ordered([
            "Choix du fil rouge : idéalement devis OU relances (le coeur du temps perdu)",
            "Fiche métier et gabarits de base rédigés (cours « Prompts système » et « Bibliothèque »)",
            "Mesure de départ chronométrée : temps réel actuel du processus, sur 3 cas",
        ]),
        heading(2, "Semaine 2 : le premier gain"),
        ordered([
            "Utilisation quotidienne sur cas réels, corrections notées",
            "Premier comparatif : temps avant / temps avec la méthode",
            "Réunion de 30 minutes : qu'est-ce qui bloque ? On ajuste le gabarit, pas l'objectif",
        ]),
        callout_info("Le chrono de départ est non négociable : sans mesure initiale, aucun gain ne pourra être démontré, ni à vous-même ni à votre équipe."),
     ),
    },
    {
     "title": "Semaines 3 et 4 : extension, mesure, pérennité",
     "image_query": "growth plant business success",
     "build": lambda img: doc(
        heading(1, "Semaines 3 et 4 : extension, mesure, pérennité"),
        para("La seconde quinzaine étend ce qui marche, formalise ce qui a été appris et installe les rituels qui feront durer."),
        image(img),
        heading(2, "Semaine 3 : l'extension"),
        ordered([
            "Deuxième processus ajouté (relances si vous aviez choisi devis, et inversement)",
            "Formation éclair d'un deuxième collaborateur par le premier",
            "Charte IA une page rédigée (cours « Charte et référent ») et affichée",
        ]),
        heading(2, "Semaine 4 : la mesure et la suite"),
        ordered([
            "Bilan chiffré : temps gagné par semaine, qualité (erreurs évitées, délais tenus)",
            "Décision outillée : continuer en manuel assisté, ou passer à l'automatisation complète (Moteur à Devis, Pilote Auto) si le volume le justifie",
            "Rituel mensuel installé : 30 minutes d'équipe, gabarits maintenus, un nouvel usage testé",
        ]),
        callout_info("C'est exactement la trame de la formule Expertise d'Ordria : le fil rouge, le plan 30 jours, la charte et le référent. Vous venez d'en faire le tour : il ne reste qu'à l'appliquer à votre entreprise, et si vous voulez aller plus vite, nous sommes là pour ça."),
     ),
    },
    {
     "title": "Quiz final : le déploiement",
     "build": lambda img: doc(
        heading(1, "Quiz final : le déploiement"),
        quiz_node([
            {"q": "Comment choisir son projet fil rouge ?",
             "answers": [{"a": "Fréquent, mesurable, à faible risque", "c": True},
                        {"a": "Le plus spectaculaire", "c": False},
                        {"a": "Le plus difficile", "c": False},
                        {"a": "Au hasard", "c": False}]},
            {"q": "Quelle mesure au départ du plan 30 jours ?",
             "answers": [{"a": "Le temps réel du processus, chronométré sur 3 cas", "c": True},
                        {"a": "Aucune mesure", "c": False},
                        {"a": "Un sondage sur internet", "c": False},
                        {"a": "Le poids des classeurs", "c": False}]},
            {"q": "Que fait-on en semaine 3 ?",
             "answers": [{"a": "On étend au deuxième processus et on forme un collègue", "c": True},
                        {"a": "On abandonne", "c": False},
                        {"a": "On change d'outil", "c": False},
                        {"a": "On fait une pause", "c": False}]},
            {"q": "Que décide le bilan de la semaine 4 ?",
             "answers": [{"a": "Continuer en manuel assisté ou passer à l'automatisation complète selon le volume", "c": True},
                        {"a": "Toujours tout automatiser", "c": False},
                        {"a": "Toujours rien automatiser", "c": False},
                        {"a": "Fermer l'entreprise", "c": False}]},
            {"q": "Quel rituel pour pérenniser ?",
             "answers": [{"a": "30 minutes d'équipe par mois", "c": True},
                        {"a": "Un séminaire annuel à l'étranger", "c": False},
                        {"a": "Aucun", "c": False},
                        {"a": "Un audit surprise", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
]
