# -*- coding: utf-8 -*-
"""Catalogue B - suite Parcours 2 « L'art du prompt » (3 cours)
+ Parcours 3 « Déléguer son administratif » (5 cours, le coeur Ordria).
Ton Ordria, aucun em dash."""
from factory import (doc, heading, para, bullets, ordered, callout_info,
                     callout_warning, image, quiz_node)

COURSES = [
# ═══════════════ PARCOURS 2 (suite) ═══════════════
{
 "slug": "iterer-avec-lia",
 "title": "Itérer avec l'IA : la boucle du menuisier",
 "level": "Intermédiaire",
 "description": "Un menuisier ne mesure pas une fois : il ajuste. Avec l'IA, même logique. Ce cours enseigne la boucle d'itération efficace : demander, évaluer, affiner, livrer, en évitant les pièges qui font perdre plus de temps qu'on n'en gagne.",
 "learnings": "Maîtriser la boucle demander/évaluer/affiner, reconnaître quand arrêter d'itérer, utiliser les demandes de variantes, faire réviser son propre travail par l'IA",
 "tags": "ia, intermédiaire, parcours-prompt, iteration, methode",
 "cover_query": "carpenter workshop wood planing",
 "chapters": [
  {
   "title": "La boucle d'itération",
   "description": "Quatre tours maximum, sinon on dérape.",
   "activities": [
    {
     "title": "Demander, évaluer, affiner, livrer",
     "image_query": "woodworking measuring precision",
     "build": lambda img: doc(
        heading(1, "Demander, évaluer, affiner, livrer"),
        para("La première réponse est un bois brut. On ne recommence pas la découpe : on ajuste. Trois à quatre tours d'ajustement suffisent pour un document professionnel."),
        image(img),
        heading(2, "Tour 1 : la demande structurée (méthode 3 C)"),
        para("Vous obtenez une base correcte si le contexte était bon. Sinon, ce n'est pas la peine de polir : corrigez le contexte d'abord."),
        heading(2, "Tour 2 : la correction ciblée"),
        para("« Le paragraphe sur les garanties est trop timide : renforce-le. Garde le reste. » Une instruction, un effet."),
        heading(2, "Tour 3 : la variante"),
        para("« Propose une version 30 % plus courte et une version avec un ton plus direct. » Vous choisissez la meilleure des deux."),
        heading(2, "Tour 4 : la relecture croisée"),
        para("« Relis ce document comme un client méfiant : liste tout ce qui te chiffonne. » L'IA devient votre relectrice."),
        callout_info("Règle des 4 tours : si après 4 allers-retours le résultat ne convient pas, le problème est dans la demande initiale. Recommencez la consigne, pas la conversation."),
     ),
    },
    {
     "title": "Faire réviser son propre texte par l'IA",
     "image_query": "document red pen corrections",
     "build": lambda img: doc(
        heading(1, "Faire réviser son propre texte par l'IA"),
        para("L'usage le plus rentable et le moins connu : ce n'est pas l'IA qui écrit, c'est elle qui corrige VOTRE texte. Collez votre brouillon et demandez une relecture structurée."),
        image(img),
        ordered([
            "« Relis ce devis : identifie les phrases ambiguës, les oublis (TVA, délais, garanties) et les tournures trop techniques pour un client »",
            "« Corrige uniquement l'orthographe et la grammaire, sans changer mon ton »",
            "« Réponds à ces 3 objections qu'un client pourrait opposer à ce document »",
        ]),
        callout_warning("Piège : demander « améliore ce texte » sans préciser quoi. Vous obtiendrez un texte différent, pas meilleur. Dites quel critère compte : clarté, longueur, ton, précision."),
     ),
    },
    {
     "title": "Quiz : itérer efficacement",
     "build": lambda img: doc(
        heading(1, "Quiz : itérer efficacement"),
        quiz_node([
            {"q": "Combien de tours d'itération avant de reconsidérer la demande initiale ?",
             "answers": [{"a": "Un seul", "c": False},
                        {"a": "Environ quatre", "c": True},
                        {"a": "Vingt", "c": False},
                        {"a": "Aucun, jamais", "c": False}]},
            {"q": "La première réponse est mauvaise sur le fond. Que faire ?",
             "answers": [{"a": "Polir les phrases une à une", "c": False},
                        {"a": "Corriger le contexte de la demande initiale", "c": True},
                        {"a": "Abandonner l'IA", "c": False},
                        {"a": "Écrire en majuscules", "c": False}]},
            {"q": "Que veut dire « correction ciblée » ?",
             "answers": [{"a": "Une instruction, un effet, le reste inchangé", "c": True},
                        {"a": "Tout réécrire à chaque fois", "c": False},
                        {"a": "Changer d'assistant", "c": False},
                        {"a": "Corriger l'orthographe seulement", "c": False}]},
            {"q": "Quel est l'usage rentable et sous-estimé de l'IA ?",
             "answers": [{"a": "Écrire des poèmes", "c": False},
                        {"a": "Relire et corriger votre propre brouillon", "c": True},
                        {"a": "Choisir vos vacances", "c": False},
                        {"a": "Remplacer le comptable", "c": False}]},
            {"q": "« Améliore ce texte » est une mauvaise consigne parce que...",
             "answers": [{"a": "Elle est trop courte pour un ordinateur", "c": False},
                        {"a": "Elle ne précise pas le critère d'amélioration", "c": True},
                        {"a": "L'IA déteste les ordres", "c": False},
                        {"a": "Elle est en français", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "prompts-systeme-gabarits",
 "title": "Prompts système et gabarits réutilisables",
 "level": "Intermédiaire",
 "description": "Arrêtez de réexpliquer tout à chaque fois : construisez vos instructions permanentes (prompts système) et votre bibliothèque de gabarits. La méthode utilisée par Ordria pour industrialiser devis, relances et emails chez ses clients.",
 "learnings": "Écrire un prompt système métier, structurer une bibliothèque de gabarits, utiliser les projets et instructions personnalisées, faire évoluer ses gabarits avec le temps",
 "tags": "ia, intermédiaire, parcours-prompt, gabarits, productivite",
 "cover_query": "templates files organized office",
 "chapters": [
  {
   "title": "Le prompt système : votre mode d'emploi permanent",
   "description": "L'instruction qui travaille pour vous à chaque conversation.",
   "activities": [
    {
     "title": "Écrire son prompt système métier",
     "image_query": "blueprint architecture plan",
     "build": lambda img: doc(
        heading(1, "Écrire son prompt système métier"),
        para("Un prompt système est un mode d'emploi permanent : il s'applique à toute la conversation sans que vous ayez à le répéter. Les assistants grand public l'appellent « instructions personnalisées » ou « mémoire » ; les versions pro parlent de « projets »."),
        image(img),
        heading(2, "Le squelette d'un bon prompt système"),
        ordered([
            "Identité : « Tu es l'assistant administratif d'un plombier chauffagiste à Bordeaux »",
            "Standards : « Tout devis mentionne : délai d'intervention, garantie pièces et main d'oeuvre, TVA 20 %, conditions de paiement à 30 jours »",
            "Ton : « Direct, rassurant, zéro jargon technique non expliqué »",
            "Interdits : « Jamais de promesse de délai inférieure à 48 h. Jamais de remise supérieure à 5 % sans mon accord »",
        ]),
        para("Une fois posé, chaque demande devient courte : « devis pour remplacement chaudière, 2 journées de travail, 2 400 euros de matériel » et le document sort complet."),
        callout_info("C'est exactement la méthode qu'Ordria déploie dans ses packs automatisation : les instructions vivent avec l'outil et travaillent à chaque usage."),
     ),
    },
    {
     "title": "Constituer sa bibliothèque de gabarits",
     "image_query": "recipe book kitchen",
     "build": lambda img: doc(
        heading(1, "Constituer sa bibliothèque de gabarits"),
        para("Un gabarit, c'est votre prompt le plus réussi, noté une fois pour toutes. Au bout de trois mois, un artisan a typiquement 8 à 15 gabarits qui couvrent 80 % de son administratif."),
        image(img),
        heading(2, "Les 10 gabarits de base d'une TPE"),
        bullets([
            "Devis détaillé à partir des lignes de travail",
            "Relance courtoise de facture impayée (3 niveaux de fermeté)",
            "Email de confirmation de rendez-vous",
            "Réponse à une demande de devis par message",
            "Compte rendu de chantier ou d'intervention",
            "Annonce de service pour réseaux sociaux",
            "Réponse à un avis client (positif et négatif)",
            "Fiche produit pour un site de commerce",
            "Demande de devis fournisseur",
            "Relance de panier abandonné (e-commerce)",
        ]),
        para("Conservez-les dans une note téléphone ou un document, avec un titre clair. Chaque gabarit gagne à contenir : le contexte métier, la structure attendue, un exemple rempli."),
        callout_warning("Piège : garder des gabarits qui « marchent presque ». Un gabarit se corrige à chaque usage : ajoutez en commentaire la correction faite (« ne pas mettre la TVA sur la remise »). C'est ainsi qu'il devient vraiment vôtre."),
     ),
    },
    {
     "title": "Quiz : prompts système et gabarits",
     "build": lambda img: doc(
        heading(1, "Quiz : prompts système et gabarits"),
        quiz_node([
            {"q": "Qu'est-ce qu'un prompt système ?",
             "answers": [{"a": "Une instruction permanente qui s'applique à toute la conversation", "c": True},
                        {"a": "Un mot de passe", "c": False},
                        {"a": "Un logiciel payant", "c": False},
                        {"a": "Une erreur système", "c": False}]},
            {"q": "Combien de gabarits couvrent typiquement 80 % de l'administratif d'une TPE ?",
             "answers": [{"a": "2", "c": False},
                        {"a": "8 à 15", "c": True},
                        {"a": "150", "c": False},
                        {"a": "Aucun", "c": False}]},
            {"q": "Que doit contenir un bon gabarit ?",
             "answers": [{"a": "Contexte métier, structure attendue, un exemple rempli", "c": True},
                        {"a": "Uniquement le mot « devis »", "c": False},
                        {"a": "Une image de chat", "c": False},
                        {"a": "Le prix de l'abonnement", "c": False}]},
            {"q": "Un gabarit « marche presque ». Que faire ?",
             "answers": [{"a": "Le supprimer", "c": False},
                        {"a": "L'enrichir de la correction à chaque usage", "c": True},
                        {"a": "Ne jamais y retoucher", "c": False},
                        {"a": "Le vendre", "c": False}]},
            {"q": "Quel avantage principal du prompt système ?",
             "answers": [{"a": "Il évite de répéter le contexte à chaque conversation", "c": True},
                        {"a": "Il rend l'abonnement gratuit", "c": False},
                        {"a": "Il accélère internet", "c": False},
                        {"a": "Il remplace le comptable", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "bibliotheque-prompts-metier",
 "title": "Bibliothèque de prompts : devis, relances, emails, annonces",
 "level": "Intermédiaire",
 "description": "30 formulations prêtes à l'emploi, testées terrain, classées par situation : devis, relances, emails difficiles, annonces, avis clients. À copier, adapter à votre métier et ranger dans vos notes.",
 "learnings": "Repartir avec 30 prompts métier prêts, savoir adapter un prompt à son activité, connaître les formulations qui marchent pour les situations délicates",
 "tags": "ia, intermédiaire, parcours-prompt, bibliotheque, prompts, pratique",
 "cover_query": "library bookshelf tools",
 "chapters": [
  {
   "title": "Devis et communication commerciale",
   "description": "Les formulations qui vendent sans surpromettre.",
   "activities": [
    {
     "title": "10 prompts devis et commerce",
     "image_query": "invoice paperwork desk",
     "build": lambda img: doc(
        heading(1, "10 prompts devis et commerce"),
        para("Chaque prompt suppose collé votre fiche métier en début de conversation (voir cours « Donner le contexte métier »). Copiez, adapter, rangez."),
        image(img),
        heading(2, "La série devis"),
        ordered([
            "« Rédige un devis professionnel pour : [travaux]. Structure : présentation, détail des postes, matériel et main d'oeuvre séparés, délai, garanties, conditions de paiement, validité 30 jours »",
            "« Réécris ce devis pour un client qui compare 3 prestataires : mets en avant la valeur, pas le prix »",
            "« Simplifie ce devis pour un particulier : retire le jargon, explique chaque poste en une phrase »",
            "« Rédige un email d'envoi du devis : chaleureux, propose un créneau d'appel, sans pression »",
            "« Relance ce devis sans réponse depuis 10 jours : courtoise, une seule relance, propose une variante budgétaire »",
        ]),
        heading(2, "La série annonces et annonces"),
        ordered([
            "« Écris une annonce de service pour Facebook Marketplace : [service], [zone], ton direct, avec 3 questions que se posent les clients avant d'appeler »",
            "« 5 titres d'annonce pour ma page Google : moins de 30 caractères, sans superlatif interdit »",
            "« Décris ce service (collage du texte) en 3 versions : particulier, professionnel, urgent »",
        ]),
        callout_info("Astuce : après chaque prompt réussi, demandez « reformule ce prompt pour qu'il soit réutilisable avec des crochets à compléter ». Vous fabriquez le gabarit automatiquement."),
     ),
    },
    {
     "title": "10 prompts relances et emails délicats",
     "image_query": "writing email laptop office",
     "build": lambda img: doc(
        heading(1, "10 prompts relances et emails délicats"),
        para("Les emails qu'on repousse sont exactement ceux que l'IA rédige le mieux, parce qu'ils demandent du doigté plus que de la technique."),
        image(img),
        heading(2, "La série relances"),
        ordered([
            "« Relance courtoise de facture impayée depuis 15 jours : fermeté 2 sur 5, rappel des conditions, propose un échéancier »",
            "« Relance niveau 2 (35 jours) : fermeté 4 sur 5, rappelle les pénalités sans les brandir »",
            "« Relance de devis sans réponse : une question ouverte finale, une seule »",
            "« Email de retard d'exécution prévenu à l'avance : excuse courte, nouvelle date ferme, geste commercial »",
        ]),
        heading(2, "La série situations délicates"),
        ordered([
            "« Réponse à un client mécontent d'une facture : calme, factuel, propose un point téléphonique cette semaine »",
            "« Réponse à un avis Google négatif injustifié : policé, factuel, orienté solution, sans dispute publique »",
            "« Refus d'une demande de remise excessive : valorise le travail, propose une alternative dans le budget »",
            "« Annonce d'une augmentation de tarifs aux clients fidèles : raison, préavis, geste pour les anciens »",
            "« Demande de témoignage client : 3 questions simples, promesse de 2 minutes »",
            "« Email de fin de collaboration avec un client difficile : professionnel, sans règlement de comptes »",
        ]),
        callout_warning("Règle : l'IA prépare, vous relisez TOUTE communication de conflit. Le ton juste, c'est vous qui le jugez, pas elle."),
     ),
    },
    {
     "title": "Quiz : la bibliothèque",
     "build": lambda img: doc(
        heading(1, "Quiz : la bibliothèque"),
        quiz_node([
            {"q": "Quels emails l'IA rédige-t-elle le mieux ?",
             "answers": [{"a": "Ceux qu'on repousse : ils demandent du doigté", "c": True},
                        {"a": "Les virements bancaires", "c": False},
                        {"a": "Les contrats de travail", "c": False},
                        {"a": "Aucun email", "c": False}]},
            {"q": "Quel niveau de fermeté pour une relance à 15 jours ?",
             "answers": [{"a": "Menaces immédiates", "c": False},
                        {"a": "Fermeté 2 sur 5, avec proposition d'échéancier", "c": True},
                        {"a": "Fermeté maximale", "c": False},
                        {"a": "Aucune relance", "c": False}]},
            {"q": "Comment fabriquer un gabarit après un prompt réussi ?",
             "answers": [{"a": "En demandant de le reformuler avec des crochets à compléter", "c": True},
                        {"a": "En le supprimant", "c": False},
                        {"a": "En l'imprimant", "c": False},
                        {"a": "En le changeant de langue", "c": False}]},
            {"q": "Qui doit relire une communication de conflit ?",
             "answers": [{"a": "Personne", "c": False},
                        {"a": "Vous, toujours", "c": True},
                        {"a": "Le client", "c": False},
                        {"a": "L'assistant IA seul", "c": False}]},
            {"q": "Que faire avant d'utiliser un prompt de la bibliothèque ?",
             "answers": [{"a": "Coller sa fiche métier en début de conversation", "c": True},
                        {"a": "Payer un abonnement", "c": False},
                        {"a": "Éteindre le téléphone", "c": False},
                        {"a": "Rien", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
# ═══════════════ PARCOURS 3 : DÉLÉGUER SON ADMINISTRATIF ═══════════════
{
 "slug": "devis-automatises",
 "title": "Devis automatisés : d'un appel client au PDF prêt",
 "level": "Intermédiaire",
 "description": "Le chantier roi de l'automatisation : produire un devis complet, personnalisé et professionnel en moins de 5 minutes. Méthode pas à pas, de la prise de notes sur le terrain au PDF envoyé, avec ou sans outils automatisés.",
 "learnings": "Structurer une note de terrain devenue devis, réduire le temps par devis de 20 à 5 minutes, limiter les oublis coûteux, préparer l'automatisation complète",
 "tags": "ia, intermédiaire, parcours-administratif, devis, automatisation, metiers",
 "cover_query": "construction blueprint site plans",
 "chapters": [
  {
   "title": "Du chantier au devis en 5 minutes",
   "description": "La chaîne complète, étape par étape.",
   "activities": [
    {
     "title": "La méthode des 5 minutes chrono",
     "image_query": "worker phone notes construction",
     "build": lambda img: doc(
        heading(1, "La méthode des 5 minutes chrono"),
        para("Le devis lent n'est pas lent à écrire : il est lent à RECONSTRUIRE. La méthode : capturer les bonnes informations sur place, une seule fois, puis laisser le gabarit faire le travail."),
        image(img),
        heading(2, "Minute 1 : la note structurée sur le terrain"),
        para("Dictée vocale ou notes rapides, toujours les mêmes 6 rubriques : client et lieu, besoin exprimé, travaux constatés, matériel prévu, temps estimé, contraintes (accès, délai, préférences)."),
        heading(2, "Minutes 2 et 3 : la transformation"),
        para("Collez la note avec votre gabarit devis : « Transforme cette note en devis complet selon nos standards ». La structure sort : postes détaillés, matériel et main d'oeuvre séparés, TVA correcte."),
        heading(2, "Minutes 4 et 5 : la vérification et l'envoi"),
        para("Les 3 verrous (chiffres, noms, promesses), puis génération du PDF et email d'envoi rédigé par l'IA avec proposition de créneau."),
        callout_info("Ordria déploie exactement cette chaîne en version entièrement automatique dans son Moteur à Devis : la note de terrain devient un devis prêt à envoyer, avec suivi jusqu'à signature. Ce cours vous donne la méthode manuelle qui fait déjà gagner 75 % du temps."),
     ),
    },
    {
     "title": "Les oublis qui coûtent cher",
     "image_query": "calculator money finance",
     "build": lambda img: doc(
        heading(1, "Les oublis qui coûtent cher"),
        para("Un devis incomplet se paie deux fois : en marge oubliée et en litige. La checklist anti-oubli, à intégrer dans votre gabarit."),
        image(img),
        bullets([
            "Frais de déplacement et d'accès (échafaudage, nacelle)",
            "Gestion des déchets et évacuation",
            "Temps d'approvisionnement, pas seulement de pose",
            "TVA correcte par poste (rénovation énergique : taux différents)",
            "Conditions de paiement et acompte",
            "Validité du devis (30 jours protège des hausses de prix)",
            "Exclusions claires : ce qui n'est PAS compris",
        ]),
        callout_warning("La ligne la plus rentable d'un devis est souvent « exclusions ». Trois mots qui évitent dix litiges : « hors dépose d'existant », « hors rebouchage », « hors hors défauts cachés »."),
     ),
    },
    {
     "title": "Quiz : devis au chrono",
     "build": lambda img: doc(
        heading(1, "Quiz : devis au chrono"),
        quiz_node([
            {"q": "Pourquoi un devis est-il lent à produire ?",
             "answers": [{"a": "Parce qu'on reconstruit les informations après coup", "c": True},
                        {"a": "Parce que l'ordinateur est lent", "c": False},
                        {"a": "À cause de la TVA", "c": False},
                        {"a": "Parce que le client appelle", "c": False}]},
            {"q": "Combien de rubriques dans la note terrain ?",
             "answers": [{"a": "6 : client, besoin, travaux, matériel, temps, contraintes", "c": True},
                        {"a": "1 : le prix", "c": False},
                        {"a": "30", "c": False},
                        {"a": "Aucune", "c": False}]},
            {"q": "Quelle ligne de devis évite le plus de litiges ?",
             "answers": [{"a": "La remise", "c": False},
                        {"a": "Les exclusions claires", "c": True},
                        {"a": "Le logo", "c": False},
                        {"a": "La date d'anniversaire du client", "c": False}]},
            {"q": "Quel temps réaliste pour un devis complet avec la méthode ?",
             "answers": [{"a": "5 minutes", "c": True},
                        {"a": "2 jours", "c": False},
                        {"a": "1 heure", "c": False},
                        {"a": "20 minutes", "c": False}]},
            {"q": "Que fait le Moteur à Devis d'Ordria en plus ?",
             "answers": [{"a": "Il automatise la chaîne complète avec suivi jusqu'à signature", "c": True},
                        {"a": "Il appelle le client à votre place", "c": False},
                        {"a": "Il monte l'échafaudage", "c": False},
                        {"a": "Rien", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "relances-automatiques",
 "title": "Relances clients sans y penser : emails et SMS automatiques",
 "level": "Intermédiaire",
 "description": "L'argent dort dans les factures impayées et les devis sans réponse. Ce cours construit votre système de relances à 3 niveaux : courtois, ferme, final. Programmé une fois, il travaille pendant que vous travaillez.",
 "learnings": "Construire une séquence de relance en 3 niveaux, choisir email ou SMS, programmer sans outil complexe, récupérer de l'argent sans fâcher les clients",
 "tags": "ia, intermédiaire, parcours-administratif, relances, tresorerie, automatisation",
 "cover_query": "calendar reminder clock",
 "chapters": [
  {
   "title": "Le système des 3 niveaux",
   "description": "Fermeté progressive, zéro agressivité.",
   "activities": [
    {
     "title": "Construire sa séquence de relance",
     "image_query": "stacked letters mail",
     "build": lambda img: doc(
        heading(1, "Construire sa séquence de relance"),
        para("Une bonne relance ressemble à une échelle : on monte d'un cran seulement si le précédent n'a rien donné. Trois niveaux suffisent dans 90 % des cas."),
        image(img),
        heading(2, "Niveau 1 (J+15) : le rappel courtois"),
        para("Le ton : « la facture a peut-être échappé à votre attention ». Fermeté 2 sur 5. Toujours proposer un règlement en ligne ou un échéancier si le client a une difficulté."),
        heading(2, "Niveau 2 (J+35) : le rappel ferme"),
        para("Le ton : rappel des conditions, pénalités mentionnées sans être brandies. Fermeté 4 sur 5. Demande une date de règlement précise."),
        heading(2, "Niveau 3 (J+60) : la lettre finale"),
        para("Dernier message avant procédure : facture rectificative avec pénalités calculées, mise en demeure préparée par l'IA, relue par vous ou votre avocat."),
        callout_info("Statistique métier : 70 % des impayés se règlent au niveau 1, 20 % au niveau 2. Le niveau 3 reste rare : c'est fait pour."),
     ),
    },
    {
     "title": "Programmer sans y penser",
     "image_query": "smartphone notifications phone",
     "build": lambda img: doc(
        heading(1, "Programmer sans y penser"),
        para("Trois niveaux d'automatisation, selon vos outils. L'important : le déclencheur doit être la DATE, jamais votre mémoire."),
        image(img),
        ordered([
            "Niveau débutant : rappel calendrier à J+15, J+35, J+60 à la création de chaque facture, avec le gabarit de relance prêt dans vos notes",
            "Niveau intermédiaire : votre logiciel de facturation programme les relances emails automatiques (la plupart le font, peu l'activent)",
            "Niveau avancé : le Pilote Auto des Relances d'Ordria enchaîne email et SMS, adapte le ton selon le client et vous alerte seulement quand une décision humaine est nécessaire",
        ]),
        para("Le SMS double l'efficacité de la relance niveau 1 : 98 % de taux de lecture. Une ligne suffit : « Bonjour [Prénom], petit rappel de la facture [n°] du [date], montant [X]. Lien de paiement : [lien]. Merci ! »"),
        callout_warning("Piège : relancer TROP tôt ou TROP souvent. Le client correct se fâche d'un rappel à J+3. La séquence 15/35/60 est calée sur les délais de paiement usuels des TPE."),
     ),
    },
    {
     "title": "Quiz : relances",
     "build": lambda img: doc(
        heading(1, "Quiz : relances"),
        quiz_node([
            {"q": "Quand déclencher la relance niveau 1 ?",
             "answers": [{"a": "À J+15 après échéance", "c": True},
                        {"a": "Le jour même", "c": False},
                        {"a": "Après un an", "c": False},
                        {"a": "Jamais", "c": False}]},
            {"q": "Quel pourcentage d'impayés se règle aux niveaux 1 et 2 ?",
             "answers": [{"a": "10 %", "c": False},
                        {"a": "Environ 90 %", "c": True},
                        {"a": "50 %", "c": False},
                        {"a": "100 %", "c": False}]},
            {"q": "Pourquoi le SMS est-il efficace en niveau 1 ?",
             "answers": [{"a": "Il est gratuit", "c": False},
                        {"a": "Taux de lecture de 98 %", "c": True},
                        {"a": "Il fait peur", "c": False},
                        {"a": "Il est joli", "c": False}]},
            {"q": "Que doit être le déclencheur d'une relance ?",
             "answers": [{"a": "Votre mémoire", "c": False},
                        {"a": "La date d'échéance", "c": True},
                        {"a": "Votre humeur", "c": False},
                        {"a": "La météo", "c": False}]},
            {"q": "Que fait le Pilote Auto des Relances d'Ordria ?",
             "answers": [{"a": "Il enchaîne emails et SMS et vous alerte quand une décision humaine est requise", "c": True},
                        {"a": "Il envoie des huissiers", "c": False},
                        {"a": "Il détruit les factures", "c": False},
                        {"a": "Rien du tout", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "factures-ocr-classement",
 "title": "Factures, OCR et classement documentaire",
 "level": "Intermédiaire",
 "description": "La paperasse disparaît enfin : photographiez une facture, l'IA lit les montants, TVA et coordonnées, prépare la saisie comptable et range le document. Méthode applicable dès demain avec un simple téléphone.",
 "learnings": "Utiliser l'OCR assisté par IA pour les factures, préparer une saisie comptable fiable, classer pour retrouver en 10 secondes, sécuriser la conservation RGPD",
 "tags": "ia, intermédiaire, parcours-administratif, factures, ocr, comptabilite",
 "cover_query": "paperwork documents organize",
 "chapters": [
  {
   "title": "La facture photographiée devient saisie",
   "description": "Du photo au tableau comptable propre.",
   "activities": [
    {
     "title": "L'OCR assisté : 80 % du travail fait",
     "image_query": "camera phone photograph document",
     "build": lambda img: doc(
        heading(1, "L'OCR assisté : 80 % du travail fait"),
        para("L'OCR (reconnaissance de texte) existe depuis longtemps. Ce que l'IA ajoute : la COMPREHENSION. Elle ne lit pas seulement « Total 1 240,00 », elle sait que c'est le TTC, isole la TVA, identifie le fournisseur et la catégorie de dépense probable."),
        image(img),
        heading(2, "La routine en 4 gestes"),
        ordered([
            "Photographiez la facture à plat, bon éclairage (le téléphone dans une poche de veste, toujours le même endroit)",
            "Envoyez la photo à votre assistant avec le gabarit : « Extrais : fournisseur, date, montant HT, TVA, TTC, catégorie probable. Présente en tableau »",
            "Contrôlez les 3 chiffres clés en 10 secondes",
            "Transmettez le tableau au classement ou à votre comptable",
        ]),
        callout_info("Les cabinets comptables équipés par Ordria font relire l'OCR par l'IA, puis par un oeil humain : le taux d'erreur tombe sous 0,5 %, contre 3 à 5 % en saisie manuelle fatiguée."),
     ),
    },
    {
     "title": "Classer pour retrouver en 10 secondes",
     "image_query": "filing cabinet folders",
     "build": lambda img: doc(
        heading(1, "Classer pour retrouver en 10 secondes"),
        para("Un classement utile se juge à la RECHERCHE, pas au rangement. La règle : un nom de fichier qui parle, une arborescence plate, une convention unique."),
        image(img),
        heading(2, "La convention de nommage qui marche"),
        para("AAAAMMJJ_type_fournisseur_montant : « 20260315_facture_QuincaillerieDupon_456ht.pdf ». L'IA génère ce nom automatiquement depuis l'OCR : demandez « renomme ce fichier selon notre convention »."),
        heading(2, "Que garder, combien de temps ?"),
        bullets([
            "Factures d'achat et de vente : 10 ans (obligation comptable)",
            "Devis non acceptés : 2 ans suffisent",
            "Documents RH : durées spécifiques, demander au comptable",
            "Tout ce qui contient des données clients : accès restreint, à vie de la relation",
        ]),
        callout_warning("Piège RGPD : le dossier « factures » sur le bureau partagé de l'atelier. Les données bancaires de vos clients méritent un accès protégé, pas un dossier ouvert à tous."),
     ),
    },
    {
     "title": "Quiz : factures et OCR",
     "build": lambda img: doc(
        heading(1, "Quiz : factures et OCR"),
        quiz_node([
            {"q": "Qu'apporte l'IA en plus de l'OCR classique ?",
             "answers": [{"a": "La compréhension : TVA, fournisseur, catégorie", "c": True},
                        {"a": "Une meilleure photocopie", "c": False},
                        {"a": "Le wifi", "c": False},
                        {"a": "Rien", "c": False}]},
            {"q": "Après extraction OCR, que contrôle-t-on en priorité ?",
             "answers": [{"a": "Les 3 chiffres clés (HT, TVA, TTC)", "c": True},
                        {"a": "La couleur du papier", "c": False},
                        {"a": "Le numéro de page", "c": False},
                        {"a": "La police d'écriture", "c": False}]},
            {"q": "Combien de temps conserver les factures d'achat ?",
             "answers": [{"a": "10 ans", "c": True},
                        {"a": "10 jours", "c": False},
                        {"a": "À vie", "c": False},
                        {"a": "6 mois", "c": False}]},
            {"q": "Un bon classement se juge sur quoi ?",
             "answers": [{"a": "La beauté des dossiers", "c": False},
                        {"a": "La vitesse de RECHERCHE", "c": True},
                        {"a": "Le nombre de sous-dossiers", "c": False},
                        {"a": "La couleur des étiquettes", "c": False}]},
            {"q": "Que faire d'un dossier factures ouvert à tout l'atelier ?",
             "answers": [{"a": "Rien, c'est pratique", "c": False},
                        {"a": "Restreindre l'accès : données bancaires clients", "c": True},
                        {"a": "L'imprimer", "c": False},
                        {"a": "Le supprimer", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "emails-comptes-rendus-5min",
 "title": "Emails et comptes rendus dictés en 5 minutes",
 "level": "Intermédiaire",
 "description": "Vos mains sont occupées, pas votre voix. La méthode des pros de terrain : dicter en marchant, laisser l'IA structurer, relire en arrivant. Comptes rendus de chantier, rapports d'intervention, emails du soir : la journée se termine à l'heure.",
 "learnings": "Dicter des notes exploitables, faire structurer un compte rendu complet par l'IA, utiliser la dictée mobile au quotidien, tenir le rythme sans rédiger le soir",
 "tags": "ia, intermédiaire, parcours-administratif, dictee, comptes-rendus, mobile",
 "cover_query": "construction site engineer walking helmet",
 "chapters": [
  {
   "title": "Dicter en marchant",
   "description": "La voix comme outil de productivité de terrain.",
   "activities": [
    {
     "title": "La dictée structurée en 90 secondes",
     "image_query": "voice recording microphone phone",
     "build": lambda img: doc(
        heading(1, "La dictée structurée en 90 secondes"),
        para("La dictée est le super-pouvoir des métiers de terrain. La règle unique : annoncez la STRUCTURE en dictant, l'IA reconstruit tout le reste."),
        image(img),
        heading(2, "Le modèle de dictée chantier"),
        para("« Compte rendu chantier Dupont, 14 rue des Lilas. Points faits : pose des rails, préparation du sol. Points restants : carrelage, plinthes. Problème : livraison carrelage retardée de 2 jours. Décision : on décale la fin au vendredi. Matériel à commander : colle 2 sacs, croisillons. Photos prises. Fin. »"),
        heading(2, "La transformation"),
        para("Collez la dictée : « Mets en compte rendu professionnel : sections Travaux réalisés, Travaux restants, Points de blocage, Décisions, Matériel. Ton factuel pour le client et l'équipe. » Vous obtenez un document propre, prêt à envoyer ou archiver."),
        callout_info("Le réflexe qui change les journées : la dictée se fait DANS la voiture en quittant le chantier, pas le soir sur la table de la cuisine. 90 secondes sur place valent 20 minutes de mémoire refroidie."),
     ),
    },
    {
     "title": "Les emails du soir traités en 10 minutes",
     "image_query": "evening desk computer relax",
     "build": lambda img: doc(
        heading(1, "Les emails du soir traités en 10 minutes"),
        para("La pile d'emails du soir, c'est souvent 8 messages qui se traitent en 3 phrases chacun. L'IA les rédige tous pendant que vous vérifiez le premier."),
        image(img),
        heading(2, "La technique du passage groupé"),
        ordered([
            "Copiez les 3 emails les plus importants dans l'assistant, avec votre fiche métier",
            "Demandez : « Pour chacun : réponse en 5 phrases maximum, ton professionnel, une action claire (créneau, validation, information) »",
            "Relisez et envoyez un par un",
            "Recommencez pour les suivants",
        ]),
        para("Temps constaté : 10 minutes pour une quinzaine de réponses correctes. Le soir libéré, c'est du temps de vie récupéré."),
        callout_warning("Piège : répondre sous la colère à un email agressif. L'IA excelle aussi ici : « réécris ma réponse en enlevant toute l'agressivité, garde les faits ». Envoyé demain matin, relu à froid."),
     ),
    },
    {
     "title": "Quiz : dicter et structurer",
     "build": lambda img: doc(
        heading(1, "Quiz : dicter et structurer"),
        quiz_node([
            {"q": "Quand dicter son compte rendu de chantier ?",
             "answers": [{"a": "Dans la voiture en quittant le chantier", "c": True},
                        {"a": "Le dimanche soir", "c": False},
                        {"a": "Le mois suivant", "c": False},
                        {"a": "Jamais", "c": False}]},
            {"q": "Que faut-il annoncer en dictant pour que l'IA structure bien ?",
             "answers": [{"a": "La structure (points faits, restants, problèmes...)", "c": True},
                        {"a": "Sa couleur préférée", "c": False},
                        {"a": "Rien du tout", "c": False},
                        {"a": "Le prix du carburant", "c": False}]},
            {"q": "Comment traiter une pile d'emails du soir ?",
             "answers": [{"a": "Un par un pendant 2 heures", "c": False},
                        {"a": "Par passages groupés : l'IA rédige, vous relisez", "c": True},
                        {"a": "En les supprimant", "c": False},
                        {"a": "En téléphonant à chacun", "c": False}]},
            {"q": "Que faire d'une réponse écrite sous la colère ?",
             "answers": [{"a": "L'envoyer immédiatement", "c": False},
                        {"a": "Demander à l'IA d'enlever l'agressivité, envoyer relu à froid", "c": True},
                        {"a": "La poster sur les réseaux", "c": False},
                        {"a": "La cadenasser", "c": False}]},
            {"q": "Combien de temps pour une quinzaine de réponses correctes avec l'IA ?",
             "answers": [{"a": "Environ 10 minutes", "c": True},
                        {"a": "3 heures", "c": False},
                        {"a": "Toute la nuit", "c": False},
                        {"a": "1 seconde", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "tableau-de-bord-metier",
 "title": "Tableau de bord métier : piloter son activité",
 "level": "Avancé",
 "description": "Cours avancé : construire le tableau de bord qui répond aux 5 questions vitales (combien je facture, qui me doit quoi, quels devis signent, où part mes heures). De l'export brut à la vision claire, avec l'IA comme analyste.",
 "learnings": "Définir ses 5 indicateurs vitaux, transformer un export en tableau de bord lisible, faire analyser ses chiffres par l'IA, prendre des décisions données à l'appui",
 "tags": "ia, avancé, parcours-administratif, pilotage, indicateurs, direction",
 "cover_query": "dashboard analytics charts screen",
 "chapters": [
  {
   "title": "Vos 5 chiffres vitaux",
   "description": "Le pilotage commence par le choix de ce qu'on regarde.",
   "activities": [
    {
     "title": "Choisir ses indicateurs (et rien d'autre)",
     "image_query": "business charts graph growth",
     "build": lambda img: doc(
        heading(1, "Choisir ses indicateurs (et rien d'autre)"),
        para("Un tableau de bord qui dépasse 5 indicateurs ne sert plus à rien : on le regarde sans le lire. En voici la version minimale vitale pour une TPE de services ou de travaux."),
        image(img),
        ordered([
            "Chiffre d'affaires du mois et projection (basée sur devis signés)",
            "Créances clients : qui me doit quoi, depuis combien de temps",
            "Taux de signature des devis (signés / envoyés)",
            "Heures vendues vs heures travaillées (le némésis des artisans)",
            "Trésorerie disponible à 30 jours (encaissements prévus moins charges connues)",
        ]),
        para("Ces 5 chiffres répondent aux questions qui réveillent à 3 heures du matin. Le reste est du détail qui se consulte quand un problème apparaît."),
     ),
    },
    {
     "title": "L'IA analyste : de l'export au diagnostic",
     "image_query": "spreadsheet laptop analysis",
     "build": lambda img: doc(
        heading(1, "L'IA analyste : de l'export au diagnostic"),
        para("Votre logiciel exporte des listes brutes. L'IA les transforme en réponses. C'est LE usage avancé le plus rentable de l'IA en TPE : l'analyse de données sans data analyst."),
        image(img),
        heading(2, "La séquence d'analyse mensuelle (20 minutes)"),
        ordered([
            "Exportez factures, devis et relances du mois (CSV ou copier-coller du tableau)",
            "Collez dans l'assistant : « Voici mes factures, devis et relances du mois. Calcule : CA facturé, CA signé non facturé, taux de signature, top 3 clients, encours clients par ancienneté. Présente en tableau »",
            "Enchaînez : « Compare au mois précédent (données ci-dessous). 3 enseignements, 3 actions concrètes pour le mois prochain »",
        ]),
        para("L'IA calcule sans fatigue et remarque ce que l'oeil fatigué ne voit plus : le client qui paie toujours à 60 jours, le type de devis qui signe deux fois plus."),
        callout_info("Le Tableau de Bord Métier d'Ordria automatise toute cette chaîne : connecté à vos outils, il se met à jour seul et alerte sur les dérives. Ce cours vous apprend à le faire à la main, et surtout à LIRE ce qu'il vous dit."),
        callout_warning("Prudence : ne donnez jamais à un assistant public des exports contenant les données bancaires complètes de vos clients. Anonymisez les noms : client A, B, C. L'analyse est aussi bonne, le risque nul."),
     ),
    },
    {
     "title": "Quiz : pilotage",
     "build": lambda img: doc(
        heading(1, "Quiz : pilotage"),
        quiz_node([
            {"q": "Combien d'indicateurs dans un tableau de bord vital ?",
             "answers": [{"a": "5 maximum", "c": True},
                        {"a": "40", "c": False},
                        {"a": "Autant que possible", "c": False},
                        {"a": "Zéro", "c": False}]},
            {"q": "Que mesure le taux de signature des devis ?",
             "answers": [{"a": "La proportion de devis envoyés qui sont signés", "c": True},
                        {"a": "La météo", "c": False},
                        {"a": "Le nombre d'employés", "c": False},
                        {"a": "La taille du local", "c": False}]},
            {"q": "Quel usage avancé de l'IA le plus rentable en TPE ?",
             "answers": [{"a": "L'analyse de données sans data analyst", "c": True},
                        {"a": "Les dessins animés", "c": False},
                        {"a": "Le trading", "c": False},
                        {"a": "Les jeux vidéo", "c": False}]},
            {"q": "Avant de coller un export clients dans l'IA, que faire ?",
             "answers": [{"a": "Anonymiser les noms (client A, B, C)", "c": True},
                        {"a": "Ajouter les IBAN", "c": False},
                        {"a": "Le traduire", "c": False},
                        {"a": "Le colorier", "c": False}]},
            {"q": "Que fait le Tableau de Bord Métier d'Ordria ?",
             "answers": [{"a": "Il automatise la chaîne d'analyse et alerte sur les dérives", "c": True},
                        {"a": "Il fait le café", "c": False},
                        {"a": "Il remplace le comptable", "c": False},
                        {"a": "Rien", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
]
