# -*- coding: utf-8 -*-
"""Catalogue C - Parcours 4 « IA par métier » (6 cours intermédiaire).
Un cours par métier phare des outils Ordria : restaurant, garage, BTP,
cabinet comptable, salon et institut, commerce. Ton Ordria, aucun em dash."""
from factory import (doc, heading, para, bullets, ordered, callout_info,
                     callout_warning, image, quiz_node)

COURSES = [
{
 "slug": "ia-restaurant",
 "title": "Restaurant : réservations, commandes et stocks pilotés par l'IA",
 "level": "Intermédiaire",
 "description": "Pendant le service, vous cuisinez : l'administratif attend le soir. Ce cours montre comment un restaurant organise réservations, devis traiteur, stocks et comptes rendus avec un assistant IA, pour finir les tâches du soir en 15 minutes au lieu d'une heure.",
 "learnings": "Automatiser confirmations de réservation, produire un devis traiteur en 3 minutes, tenir les stocks avec alertes, rédiger les comptes rendus de service",
 "tags": "ia, intermédiaire, parcours-metiers, restaurant, metier, automatisation",
 "cover_query": "restaurant kitchen chef cooking",
 "chapters": [
  {
   "title": "Le back-office du service",
   "description": "Réservations, devis traiteur et stocks pendant que la cuisine tourne.",
   "activities": [
    {
     "title": "Réservations et confirmations automatiques",
     "image_query": "restaurant table setting dinner",
     "build": lambda img: doc(
        heading(1, "Réservations et confirmations automatiques"),
        para("Chaque réservation non confirmée est une table qui risque de rester vide un soir de forte affluence. L'assistant gère la mécanique : confirmation, rappel la veille, gestion des changements."),
        image(img),
        heading(2, "La séquence type"),
        ordered([
            "Réservation notée (téléphone, plateforme, passage) : nom, nombre, date, heure, occasion",
            "L'IA rédige le SMS ou email de confirmation avec le ton de la maison",
            "Rappel automatique la veille à 18 h : réduit les no-shows de moitié",
            "Après service : l'IA prépare la liste du lendemain, avec les particularités (allergies, anniversaires, tables privilégiées)",
        ]),
        callout_info("Le détail qui fidélise : l'IA retient les préférences notées (« table 4 : anniversaire de mariage, menu sans gluten ») et les ressort à la prochaine réservation. Le client se sent attendu."),
     ),
    },
    {
     "title": "Devis traiteur en 3 minutes",
     "image_query": "catering buffet food trays",
     "build": lambda img: doc(
        heading(1, "Devis traiteur en 3 minutes"),
        para("Un devis traiteur combine menu, nombre de convives, matériel, service et logistique : 6 à 8 lignes à recalculer à chaque variation. Avec votre gabarit et les tarifs en contexte, l'IA assemble tout et recalcule à chaque changement de consigne."),
        image(img),
        heading(2, "La méthode"),
        ordered([
            "Fiche contexte : vos formules (cocktail, assis, buffet), tarifs par convive, options, conditions d'acompte",
            "La demande : « devis traiteur, 60 convives, formule buffet B, sans porc pour 8, livraison à 15 h sur place, service 2 personnes »",
            "Le devis complet sort : lignes, totaux, acompte, conditions",
            "Variation express : « même devis pour 80 convives » : recalcul immédiat",
        ]),
        callout_warning("Point de vigilance food safety : l'IA ne connaît pas vos obligations d'hygiène spécifiques. Les mentions réglementaires (allergènes, traçabilité) se valident avec vos propres documents de référence, pas à la génération."),
     ),
    },
    {
     "title": "Stocks et achats sans surprise",
     "image_query": "restaurant storage pantry shelves",
     "build": lambda img: doc(
        heading(1, "Stocks et achats sans surprise"),
        para("La rupture un samedi soir et la périssable invendue sont les deux ennemis de la marge. La routine simple : photo du stock, lecture par l'IA, alerte sur les seuils."),
        image(img),
        ordered([
            "Chaque fin de semaine : photos des réserves, dictée rapide des quantités approximatives",
            "Gabarit : « Compare aux seuils ci-dessous, liste ce qui est sous le seuil, propose une commande groupée par fournisseur »",
            "Commande générée, vérification des quantités, envoi",
            "En fin de mois : « analyse les écarts entre commandes et ventes : qu'ai-je trop commandé ? »",
        ]),
        callout_info("Le réflexe qui sauve le samedi : le seuil d'alerte se place non pas à la rupture, mais à la consommation d'un week-end complet. C'est la différence entre gérer et subir."),
     ),
    },
    {
     "title": "Quiz : restaurant",
     "build": lambda img: doc(
        heading(1, "Quiz : restaurant"),
        quiz_node([
            {"q": "Quel effet du rappel automatique la veille ?",
             "answers": [{"a": "Il réduit les no-shows de moitié", "c": True},
                        {"a": "Aucun", "c": False},
                        {"a": "Il double les réservations", "c": False},
                        {"a": "Il augmente les no-shows", "c": False}]},
            {"q": "Combien de temps pour un devis traiteur avec la méthode ?",
             "answers": [{"a": "3 minutes", "c": True},
                        {"a": "3 heures", "c": False},
                        {"a": "3 jours", "c": False},
                        {"a": "30 minutes", "c": False}]},
            {"q": "Où placer le seuil d'alerte de stock ?",
             "answers": [{"a": "À la rupture", "c": False},
                        {"a": "À la consommation d'un week-end complet", "c": True},
                        {"a": "Au double du besoin", "c": False},
                        {"a": "Au hasard", "c": False}]},
            {"q": "Que retenir des préférences clients notées ?",
             "answers": [{"a": "Elles permettent d'accueillir le client comme un habitué attendu", "c": True},
                        {"a": "Rien", "c": False},
                        {"a": "Elles servent à la concurrence", "c": False},
                        {"a": "Elles sont obligatoires", "c": False}]},
            {"q": "Que valider impérativement hors IA sur un devis traiteur ?",
             "answers": [{"a": "Les mentions réglementaires (allergènes, traçabilité)", "c": True},
                        {"a": "La couleur du devis", "c": False},
                        {"a": "Le nom du fichier", "c": False},
                        {"a": "La police", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "ia-garage",
 "title": "Garage : devis réparations, pièces et planning atelier",
 "level": "Intermédiaire",
 "description": "Le devis de réparation exprès, la traque des pièces détachées et le planning atelier qui ne se chevauche plus : le back-office du garage reconstruit avec un assistant IA, pensé pour les journées à deux voitures par heure.",
 "learnings": "Produire un devis de réparation complet rapidement, gérer les commandes de pièces sans doublon, synchroniser le planning atelier, industrialiser relances et facturation",
 "tags": "ia, intermédiaire, parcours-metiers, garage, mecanique, metier",
 "cover_query": "car garage mechanic repair",
 "chapters": [
  {
   "title": "Du diagnostic au devis",
   "description": "La chaîne devis express du garage.",
   "activities": [
    {
     "title": "Le devis de réparation express",
     "image_query": "car engine diagnostic workshop",
     "build": lambda img: doc(
        heading(1, "Le devis de réparation express"),
        para("Le client attend au comptoir, la voiture est sur le pont. La note dictée depuis l'atelier devient un devis complet avant qu'il ne reparte. C'est la conversation la plus rentable du garage : celle qui signe."),
        image(img),
        heading(2, "La dictée atelier en 30 secondes"),
        para("« Renault Clio 4, 2016, 98 000 km. Diagnostic : plaquettes avant usées, disques à remplacer, liquide de frein à purger. Pièces : plaquettes ATE, disques Brembo, liquide DOT4. Temps : 1,5 h. Client pressé, départ prévu à 16 h. »"),
        heading(2, "La transformation en devis"),
        para("Le gabarit garage assemble : postes de travail, pièces référencées, temps barème, total HT/TVA/TTC, disponibilité des pièces, risque identifié (« disques : commander avant validation »). Le client signe au comptoir."),
        callout_info("L'argument qui déclenche la signature : le devis IA mentionne toujours ce qui arriverait SANS l'intervention (usure des disques sur le tambour, distance de freinage accrue). Informer, pas effrayer."),
     ),
    },
    {
     "title": "Pièces détachées : commander sans doublon",
     "image_query": "auto parts warehouse shelves",
     "build": lambda img: doc(
        heading(1, "Pièces détachées : commander sans doublon"),
        para("La pièce commandée deux fois et la rupture de la veille d'un gros devis : les deux façons classiques de perdre de l'argent au garage. L'assistant tient l'état des commandes à jour par simple dictée."),
        image(img),
        ordered([
            "À chaque commande : « commande pièce, référence, fournisseur, véhicule, chantier, délai annoncé »",
            "Le matin : « liste les commandes en retard, avec le chantier concerné et le numéro du fournisseur »",
            "À la réception : « réceptionnée, range sous référence, préviens le client du créneau possible »",
        ]),
        para("En fin de semaine, l'analyse : « pièces les plus commandées, fournisseurs les plus lents, valeur du stock dormant ». Trois questions, des décisions d'achat données à l'appui."),
        callout_warning("Piège : laisser les références approximatives. Une référence erronée commande la mauvaise pièce : faites relire chaque référence par l'IA (« vérifie la cohérence entre véhicule, année et référence »), puis validez à l'oeil."),
     ),
    },
    {
     "title": "Planning atelier : une voiture par poste, pas deux",
     "image_query": "calendar schedule planning board",
     "build": lambda img: doc(
        heading(1, "Planning atelier : une voiture par poste, pas deux"),
        para("Le chevauchement de rendez-vous coûte le double : client mécontent et mécanicien pressé. La règle IA du planning : le temps RÉEL observé, pas le temps théorique barème."),
        image(img),
        heading(2, "La routine planning"),
        ordered([
            "Rendez-vous pris avec la nature de l'intervention",
            "L'assistant estime la durée avec VOS historiques (« vidange : 45 min réels chez nous, pas 20 »)",
            "Créneaux proposés au client en tenant compte des pièces attendues",
            "Le matin : « planning du jour, alertes pièces manquantes, priorités si retard »",
        ]),
        callout_info("Astuce : demandez à l'IA de repérer les interventions récurrentes (vidanges, révisions) et de suggérer les rappels clients à 15 jours avant l'échéance. Le rendez-vous de révision arrive tout seul."),
     ),
    },
    {
     "title": "Quiz : garage",
     "build": lambda img: doc(
        heading(1, "Quiz : garage"),
        quiz_node([
            {"q": "Où dicter la note de diagnostic ?",
             "answers": [{"a": "Depuis l'atelier, pendant que la voiture est sur le pont", "c": True},
                        {"a": "Le mois suivant", "c": False},
                        {"a": "Depuis la plage", "c": False},
                        {"a": "Jamais", "c": False}]},
            {"q": "Qu'est-ce qui déclenche la signature d'un devis réparation ?",
             "answers": [{"a": "Informer ce qui arriverait sans l'intervention", "c": True},
                        {"a": "Baisser le prix de 50 %", "c": False},
                        {"a": "Parler vite", "c": False},
                        {"a": "Ne rien expliquer", "c": False}]},
            {"q": "Sur quoi l'assistant doit-il alerter chaque matin ?",
             "answers": [{"a": "Les commandes de pièces en retard", "c": True},
                        {"a": "L'horoscope", "c": False},
                        {"a": "Le prix de l'essence seulement", "c": False},
                        {"a": "Rien", "c": False}]},
            {"q": "Quelle durée utiliser pour le planning ?",
             "answers": [{"a": "Le temps barème théorique", "c": False},
                        {"a": "Le temps réel observé dans l'atelier", "c": True},
                        {"a": "Un chiffre au hasard", "c": False},
                        {"a": "Le double toujours", "c": False}]},
            {"q": "Que suggérer 15 jours avant l'échéance d'entretien ?",
             "answers": [{"a": "Un rappel client avec créneau de révision", "c": True},
                        {"a": "Rien", "c": False},
                        {"a": "Une carte postale", "c": False},
                        {"a": "Une augmentation de prix", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "ia-btp-artisan",
 "title": "BTP et artisans : du devis à la facture finale",
 "level": "Intermédiaire",
 "description": "Le cycle complet d'un chantier : devis détaillé, suivi avec photos, commandes fournisseurs, situations de travaux et facture finale. La méthode IA qui fait tenir les chantiers dans les temps et dans les marges.",
 "learnings": "Structurer un devis chantier détaillé, tenir un suivi de chantier exploitable, gérer les situations de travaux, clôturer par la facture finale sans oubli",
 "tags": "ia, intermédiaire, parcours-metiers, btp, artisan, chantier",
 "cover_query": "construction site workers building",
 "chapters": [
  {
   "title": "Le devis chantier détaillé",
   "description": "La base de tout : un devis qui protège la marge.",
   "activities": [
    {
     "title": "Le devis qui tient compte du réel",
     "image_query": "blueprint construction plan helmet",
     "build": lambda img: doc(
        heading(1, "Le devis qui tient compte du réel"),
        para("Un devis chantier se construit en trois couches : les travaux visibles, les travaux préparatoires qu'on oublie, et les aléas qu'on encadre. L'IA aide précisément sur les deux dernières, celles qui mangent la marge."),
        image(img),
        heading(2, "La structure anti-oubli"),
        ordered([
            "Postes principaux : ce que demande le client",
            "Postes préparatoires : protection, dépose, évacuation, reprises",
            "Postes encadrés : conditions d'accès, horaires, aléas traités en devis complémentaire",
            "Exclusions claires : ce qui n'est pas compris",
        ]),
        para("La dictée de visite + votre gabarit BTP produisent le devis complet, avec les ratios de votre entreprise (marge matière, temps moyen par poste)."),
        callout_info("Fait terrain : le devis complémentaire préparé par l'IA dans la journée (avec photos commentées en référence) est accepté 3 fois plus souvent que celui qui arrive une semaine après la découverte de l'aléa."),
     ),
    },
    {
     "title": "Suivi de chantier avec photos",
     "image_query": "construction site photography phone",
     "build": lambda img: doc(
        heading(1, "Suivi de chantier avec photos"),
        para("La photo horodatée est la mémoire du chantier : elle protège en cas de litige et rassure le client. Le suivi dicté en 60 secondes à chaque visite suffit."),
        image(img),
        heading(2, "Le rituel de fin de visite"),
        para("« Chantier Dupont, jour 12. Fait : enduit salle de bain, pose carrelage entrée à 60 %. Bloqué : attente faïence murale, fournisseur dit jeudi. Demain : jointage entrée, début chambre 1. Photo : mur entrée avant jointage. »"),
        para("L'IA transforme ce flux en compte rendu propre pour le client, en entrée de journal de chantier pour vous, et surtout : en pièces justificatives ordonnées si un devis complémentaire devient nécessaire."),
        callout_warning("Le piège du carnet mouillé : les notes papier ne survivent pas au chantier. La photo + la dictée + l'IA font ce que le carnet ne pourra jamais : retrouver n'importe quel détail en 10 secondes, des mois plus tard."),
     ),
    },
    {
     "title": "Situations et facture finale",
     "image_query": "invoice payment documents",
     "build": lambda img: doc(
        heading(1, "Situations et facture finale"),
        para("Sur un chantier long, la facturation par situations maintient la trésorerie. La méthode : le pourcentage d'avancement estimé à partir de votre journal, pas au doigt mouillé."),
        image(img),
        ordered([
            "Chaque situation : « d'après le journal ci-dessous, calcule l'avancement par poste, propose la situation n° X avec retenue de garantie le cas échéant »",
            "Vérification des pourcentages proposés (l'IA propose, vous tranchez)",
            "Facture finale : « clôture : liste tout ce qui a été facturé, compare au devis et aux situations, identifie les restes à facturer »",
        ]),
        callout_info("La question finale qui rapporte : « y a-t-il des travaux réalisés non prévus au devis initial ? » Les fameux petits extras jamais facturés représentent souvent plusieurs points de marge par chantier."),
     ),
    },
    {
     "title": "Quiz : BTP et artisans",
     "build": lambda img: doc(
        heading(1, "Quiz : BTP et artisans"),
        quiz_node([
            {"q": "Quelles couches un devis chantier doit-il couvrir ?",
             "answers": [{"a": "Travaux visibles, préparatoires, aléas encadrés, exclusions", "c": True},
                        {"a": "Uniquement les travaux visibles", "c": False},
                        {"a": "Le prix total seulement", "c": False},
                        {"a": "Les photos des voisins", "c": False}]},
            {"q": "Pourquoi le rituel photo + dictée de fin de visite ?",
             "answers": [{"a": "Mémoire du chantier et protection en litige", "c": True},
                        {"a": "Pour Instagram", "c": False},
                        {"a": "Parce que c'est obligatoire", "c": False},
                        {"a": "Pour occuper l'apprenti", "c": False}]},
            {"q": "Un devis complémentaire arrive vite. Effet observé ?",
             "answers": [{"a": "Accepté 3 fois plus souvent", "c": True},
                        {"a": "Toujours refusé", "c": False},
                        {"a": "Aucun effet", "c": False},
                        {"a": "Il fâche le client", "c": False}]},
            {"q": "Sur quoi baser l'avancement d'une situation de travaux ?",
             "answers": [{"a": "Sur le journal de chantier, poste par poste", "c": True},
                        {"a": "Au doigt mouillé", "c": False},
                        {"a": "Sur la météo", "c": False},
                        {"a": "Sur le moral", "c": False}]},
            {"q": "Que rapporte la question des « travaux non prévus » en clôture ?",
             "answers": [{"a": "Les extras jamais facturés : plusieurs points de marge", "c": True},
                        {"a": "Rien", "c": False},
                        {"a": "Des ennuis", "c": False},
                        {"a": "Un café", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "ia-cabinet-comptable",
 "title": "Cabinet comptable : OCR, relances et dossiers centralisés",
 "level": "Intermédiaire",
 "description": "Pour les cabinets : l'OCR avec relecture, les relances clients programmées, le suivi des dossiers et le reporting automatisé. Se recentrer sur la mission à valeur ajoutée en déléguant la mécanique répétitive.",
 "learnings": "Industrialiser l'OCR avec contrôle qualité, programmer les relances clients, centraliser le suivi des dossiers, produire des reportings automatiques",
 "tags": "ia, intermédiaire, parcours-metiers, comptable, cabinet, ocr",
 "cover_query": "accounting office desk calculator",
 "chapters": [
  {
   "title": "La chaîne OCR avec relecture",
   "description": "La saisie fiable à grande échelle.",
   "activities": [
    {
     "title": "OCR industriel : vitesse ET fiabilité",
     "image_query": "documents scanner office work",
     "build": lambda img: doc(
        heading(1, "OCR industriel : vitesse ET fiabilité"),
        para("Un cabinet traite des centaines de documents par semaine. La chaîne fiable associe trois rôles : l'OCR qui lit, l'IA qui comprend et structure, l'humain qui contrôle par exception."),
        image(img),
        heading(2, "La chaîne en 4 étapes"),
        ordered([
            "Collecte : clients, scanners, photographies mobiles, emails",
            "Extraction : fournisseur, dates, montants, TVA, mode de paiement",
            "Contrôle par exception : l'IA signale les anomalies (TVA incohérente, doublon probable, fournisseur inconnu), le reste passe",
            "Intégration au dossier avec piste d'audit (source conservée)",
        ]),
        para("Le contrôle par exception est la clé : au lieu de tout relire, on ne regarde que ce que l'IA ne comprend pas. Le temps de saisie fond, la vigilance se concentre là où elle sert."),
        callout_info("Le taux d'anomalie est le meilleur indicateur de santé de la chaîne : stable et bas, tout va bien ; en hausse soudaine, un fournisseur a changé de format ou un type de document nouveau est arrivé."),
     ),
    },
    {
     "title": "Relances clients et suivi des dossiers",
     "image_query": "organized folders archive office",
     "build": lambda img: doc(
        heading(1, "Relances clients et suivi des dossiers"),
        para("Côté clients du cabinet : les pièces manquantes et les dossiers en attente. La mécanique de relance suit la logique des 3 niveaux, adaptée à la relation conseil."),
        image(img),
        ordered([
            "État du dossier en début de semaine : « liste des dossiers avec pièces manquantes, classés par urgence fiscale »",
            "Emails de demande de pièces : précis, listés, avec date limite",
            "Relance douce à J+7, relance ferme avant échéance légale",
            "Reporting client mensuel généré : état du dossier, travaux réalisés, points d'attention",
        ]),
        para("Le reporting mensuel automatique change la relation : le client voit ce qui est fait, le cabinet démontre sa valeur sans y passer des heures."),
        callout_warning("Point de vigilance professionnel : l'IA prépare la demande de pièces, mais l'interprétation fiscale et comptable reste la responsabilité du professionnel. L'IA classe, vous jugez."),
     ),
    },
    {
     "title": "Quiz : cabinet comptable",
     "build": lambda img: doc(
        heading(1, "Quiz : cabinet comptable"),
        quiz_node([
            {"q": "Qu'est-ce que le contrôle par exception ?",
             "answers": [{"a": "Ne relire que ce que l'IA signale comme anormal", "c": True},
                        {"a": "Tout relire deux fois", "c": False},
                        {"a": "Ne rien relire", "c": False},
                        {"a": "Relire le lundi seulement", "c": False}]},
            {"q": "Quel indicateur surveiller sur la chaîne OCR ?",
             "answers": [{"a": "Le taux d'anomalie", "c": True},
                        {"a": "La couleur des scans", "c": False},
                        {"a": "Le poids des fichiers", "c": False},
                        {"a": "Le nom des fournisseurs", "c": False}]},
            {"q": "Que fait le reporting mensuel automatique pour la relation ?",
             "answers": [{"a": "Il démontre la valeur du cabinet sans y passer des heures", "c": True},
                        {"a": "Il fâche les clients", "c": False},
                        {"a": "Rien", "c": False},
                        {"a": "Il remplace la mission", "c": False}]},
            {"q": "Qui est responsable de l'interprétation fiscale ?",
             "answers": [{"a": "Le professionnel, jamais l'IA", "c": True},
                        {"a": "L'IA seule", "c": False},
                        {"a": "Le client", "c": False},
                        {"a": "Le fournisseur", "c": False}]},
            {"q": "Comment classer les dossiers avec pièces manquantes ?",
             "answers": [{"a": "Par urgence fiscale", "c": True},
                        {"a": "Par couleur", "c": False},
                        {"a": "Par ordre alphabétique du chien", "c": False},
                        {"a": "Au hasard", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "ia-salon-institut",
 "title": "Salon et institut : rendez-vous, fiches clients et réseaux sociaux",
 "level": "Intermédiaire",
 "description": "Pendant que vous coiffez, l'assistant travaille : prise de rendez-vous, rappels SMS, fiches clients intelligentes, offres de fidélité et publications Instagram. Le back-office du salon qui ne demande qu'une heure par semaine.",
 "learnings": "Automatiser rappels de rendez-vous et gestions d'absences, tenir des fiches clients utiles, animer la fidélité, produire des publications réseaux régulièrement",
 "tags": "ia, intermédiaire, parcours-metiers, salon, institut, beaute",
 "cover_query": "hair salon hairstylist working",
 "chapters": [
  {
   "title": "Le rendez-vous qui ne tombe pas à l'eau",
   "description": "Rappels, absences et remplissage des trous.",
   "activities": [
    {
     "title": "Rappels SMS et gestion des absences",
     "image_query": "sms message phone screen",
     "build": lambda img: doc(
        heading(1, "Rappels SMS et gestion des absences"),
        para("Dans un salon, un rendez-vous manqué est une recette perdue et un créneau impossible à remplir à la dernière minute. Le rappel SMS la veille à 18 h réduit les absences de moitié, c'est mécanique."),
        image(img),
        ordered([
            "Rappel SMS la veille : prénom, heure, possibilité d'annuler par réponse",
            "Annulation détectée : l'assistant propose la liste d'attente à recontacter (« qui attend ce créneau type ? »)",
            "Trou de dernière minute : message ciblé aux clientes du créneau voisin (« un créneau s'est libéré aujourd'hui à 15 h, cela vous dit ? »)",
        ]),
        callout_info("La liste d'attente est l'arme secrète des salons qui affichent complet : quelques clientes flexibles notées avec leurs disponibilités types, contactées automatiquement quand un trou se présente."),
     ),
    },
    {
     "title": "Fiches clients intelligentes et fidélité",
     "image_query": "customer card loyalty",
     "build": lambda img: doc(
        heading(1, "Fiches clients intelligentes et fidélité"),
        para("La fiche client utile n'est pas un formulaire de 20 champs : c'est 5 lignes qui font que la cliente se sent unique. Techniques, préférences, historique, vie (couleur préférée, allergies, anniversaire)."),
        image(img),
        ordered([
            "Après chaque visite, dictée de 20 secondes : « Marie : balayage ton 7, coupe longue, adore les conseils coiffage, fille mariage en juin »",
            "Avant la visite suivante, l'IA ressort la fiche : la conversation reprend où elle s'était arrêtée",
            "Fin de mois : « clientes non revues depuis 3 mois ou plus » : campagne de retour avec offre douce",
            "Offres de fidélité : « parrainage, anniversaire, après 5 visites » : l'IA rédige les messages",
        ]),
        callout_warning("Données de santé (allergies, cuir chevelu sensible) : prudence RGPD maximale, information de la cliente, accès restreint. La fiche cliente reste un document interne protégé."),
     ),
    },
    {
     "title": "Publications Instagram sans y passer ses soirées",
     "image_query": "social media phone photography",
     "build": lambda img: doc(
        heading(1, "Publications Instagram sans y passer ses soirées"),
        para("Un salon vit de sa visibilité locale. La méthode : 20 minutes le dimanche préparent la semaine, photos et textes prêts à publier aux bons moments."),
        image(img),
        ordered([
            "Photos de la semaine (avant/après, produits, ambiance) prises au fil de l'eau",
            "Le dimanche : « propose 4 publications à partir de ces photos : légende courte, hashtag locaux, appel à l'action réservation »",
            "Planification aux heures locales de forte activité",
            "Réponses aux commentaires et messages : l'IA prépare, vous validez entre deux clientes",
        ]),
        callout_info("Le format qui fonctionne en local : avant/après + disponibilités de la semaine. La cliente qui voit le résultat ET le créneau libre réserve dans la foulée."),
     ),
    },
    {
     "title": "Quiz : salon et institut",
     "build": lambda img: doc(
        heading(1, "Quiz : salon et institut"),
        quiz_node([
            {"q": "Quel effet du rappel SMS la veille ?",
             "answers": [{"a": "Absences réduites de moitié", "c": True},
                        {"a": "Aucun effet", "c": False},
                        {"a": "Plus d'absences", "c": False},
                        {"a": "Moins de clientes", "c": False}]},
            {"q": "Que faire d'un créneau annulé à la dernière minute ?",
             "answers": [{"a": "Contacter la liste d'attente adaptée", "c": True},
                        {"a": "Rien", "c": False},
                        {"a": "Fermé plus tôt toujours", "c": False},
                        {"a": "Se plaindre en ligne", "c": False}]},
            {"q": "Combien de lignes pour une fiche client utile ?",
             "answers": [{"a": "5 lignes qui rendent la cliente unique", "c": True},
                        {"a": "20 champs", "c": False},
                        {"a": "Aucune", "c": False},
                        {"a": "Un roman", "c": False}]},
            {"q": "Quelle donnée exige une prudence RGPD maximale ?",
             "answers": [{"a": "Les données de santé (allergies, sensibilités)", "c": True},
                        {"a": "La couleur préférée", "c": False},
                        {"a": "Le prénom", "c": False},
                        {"a": "La fréquence des visites", "c": False}]},
            {"q": "Quel format de publication fonctionne en local ?",
             "answers": [{"a": "Avant/après + disponibilités de la semaine", "c": True},
                        {"a": "Citations philosophiques", "c": False},
                        {"a": "Photos de vacances", "c": False},
                        {"a": "Aucun", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
{
 "slug": "ia-commerce",
 "title": "Commerce : fiches produits, SAV et paniers abandonnés",
 "level": "Intermédiaire",
 "description": "Vendre sans être bloqué par l'administratif : fiches produits en série, service client préparé, stocks synchronisés et relances de paniers abandonnés. La chaîne IA du commerce physique et en ligne.",
 "learnings": "Produire des fiches produits en série, préparer un SAV client rapide, gérer les stocks multi-canaux, relancer les paniers abandonnés efficacement",
 "tags": "ia, intermédiaire, parcours-metiers, commerce, ecommerce, boutique",
 "cover_query": "boutique shop retail store",
 "chapters": [
  {
   "title": "Vendre en ligne sans y passer ses nuits",
   "description": "Fiches produits et service client à l'échelle.",
   "activities": [
    {
     "title": "Fiches produits en série",
     "image_query": "product photography studio",
     "build": lambda img: doc(
        heading(1, "Fiches produits en série"),
        para("Une fiche produit qui vend : titre clair, bénéfice en première ligne, caractéristiques complètes, questions fréquentes anticipées. En fabriquer 20 à la main est un supplice ; avec l'IA, c'est l'affaire d'une après-midi."),
        image(img),
        ordered([
            "Préparez un exemple parfait rédigé par vous (le modèle de style)",
            "Données brutes par produit : nom, référence, matière, dimensions, couleurs, prix",
            "« Rédige les fiches au modèle ci-dessus : 3 variantes de titre, bénéfice, description, 5 caractéristiques, 3 questions fréquentes »",
            "Contrôle : cohérence des dimensions, prix, disponibilité",
        ]),
        callout_info("La question fréquente anticipée est l'arme anti-SAV : « convient-il à... ? », « quelle taille choisir ? », « comment l'entretenir ? » publiées d'avance, elles évitent des dizaines de messages."),
     ),
    },
    {
     "title": "SAV rapide et paniers abandonnés",
     "image_query": "online shopping cart laptop",
     "build": lambda img: doc(
        heading(1, "SAV rapide et paniers abandonnés"),
        para("Le SAV rapide fidélise plus que le prix. Le principe : 5 réponses types couvrent 80 % des demandes ; l'IA les adapte au cas, vous personnalisez une phrase."),
        image(img),
        heading(2, "Les 5 réponses types à préparer"),
        bullets([
            "Où est ma commande : réponse rassurante avec étapes concrètes",
            "Produit défectueux : excuse, solution immédiate (remplacement/remboursement), geste",
            "Mauvaise taille : procédure d'échange simplifiée au maximum",
            "Question avant achat : réponse experte qui vend (pas seulement qui informe)",
            "Retard transporteur : prévenir AVANT que le client ne demande",
        ]),
        heading(2, "Paniers abandonnés"),
        para("« Rappelle ce panier de manière utile : pas de pression, mais un conseil (taille, compatibilité) ou un avantage si vous en avez un. » Un seul rappel à 24 h, éventuellement un second à 72 h : au-delà, on ennuie."),
        callout_warning("Le SAV automatisé qui fâche : la réponse type envoyée telle quelle à un client irrité. Relisez tout message tendu, et pour les litiges : l'IA prépare, vous décidez et signez."),
     ),
    },
    {
     "title": "Quiz : commerce",
     "build": lambda img: doc(
        heading(1, "Quiz : commerce"),
        quiz_node([
            {"q": "Comment produire 20 fiches produits sans supplice ?",
             "answers": [{"a": "Un exemple parfait rédigé par vous + données brutes + l'IA au modèle", "c": True},
                        {"a": "Tout copier du concurrent", "c": False},
                        {"a": "Écrire chacune à la main pendant des nuits", "c": False},
                        {"a": "Ne pas faire de fiches", "c": False}]},
            {"q": "Qu'est-ce que l'arme anti-SAV d'une fiche produit ?",
             "answers": [{"a": "Les questions fréquentes anticipées", "c": True},
                        {"a": "Un prix barré", "c": False},
                        {"a": "Une musique", "c": False},
                        {"a": "Une police originale", "c": False}]},
            {"q": "Combien de réponses types couvrent la majorité du SAV ?",
             "answers": [{"a": "5", "c": True},
                        {"a": "50", "c": False},
                        {"a": "Aucune", "c": False},
                        {"a": "120", "c": False}]},
            {"q": "Rythme recommandé des rappels de panier ?",
             "answers": [{"a": "Un à 24 h, éventuellement un second à 72 h", "c": True},
                        {"a": "Tous les jours pendant un mois", "c": False},
                        {"a": "Toutes les heures", "c": False},
                        {"a": "Jamais", "c": False}]},
            {"q": "Que faire d'un message de client irrité ?",
             "answers": [{"a": "Envoyer la réponse type telle quelle", "c": False},
                        {"a": "Relire et personnaliser : l'IA prépare, vous signez", "c": True},
                        {"a": "Ignorer", "c": False},
                        {"a": "Le publier", "c": False}]},
        ]),
     ),
    },
   ],
  },
 ],
},
]
